import { HISTORICAL_CAMPAIGNS } from './historical-campaigns.mjs';
import { TACTICAL_CAMPAIGNS,scenarioTroops } from './tactical-campaigns.mjs';
import {troopCapacity} from './troop-capacity.mjs';
import { OFFICER_BY_ID } from './officer-catalog.mjs';
import { TROOPS } from './unit-stats.mjs';

export function campaignLobby(selectedId, resume) {
  const s=[...HISTORICAL_CAMPAIGNS,...TACTICAL_CAMPAIGNS].find(s=>s.id===selectedId)||HISTORICAL_CAMPAIGNS[0];
  const catalogue=s.historical?HISTORICAL_CAMPAIGNS:TACTICAL_CAMPAIGNS;
  const era=c=>c.year?`公元 ${c.year} 年`:c.era;
  const roster=(entries,side)=>entries.map((u,i)=>`<span title="${i>=6?'预备队 · ':''}统率与等级决定带兵上限"><b>${OFFICER_BY_ID[u.id].name}</b><small>${TROOPS[u.type].name}${i>=6?' · 备':''}</small><strong>${(u.troops??(side?s.enemyTroops:s.ownTroops)).toLocaleString('zh-CN')}</strong><small>上限 ${troopCapacity({...OFFICER_BY_ID[u.id],level:u.level??(side?s.enemyLevel:s.level)}).toLocaleString('zh-CN')}</small></span>`).join('');
  return `<main class="campaign-lobby">
    <header class="lobby-nav"><a class="lobby-brand" href="#" data-action="lobby"><span>君</span>三国 · 君临</a><span class="lobby-edition">战斗试玩版</span><button class="text-button" data-action="settings">存档与设置</button></header>
    <section class="lobby-hero"><div class="lobby-hero-copy"><div class="eyebrow">THREE KINGDOMS · 战役试玩</div><h1>置身名战。<br><em>由你指挥。</em></h1><p>重返历史名战，推演群英之间的攻守。<br>选择一场战役，部署诸将，亲自决定进退。</p><div class="lobby-pills"><span>各将独立带兵</span><span>自由布阵与战法</span><span>随时暂停下令</span></div></div><div class="lobby-art" aria-hidden="true"><div class="lobby-moon"></div><div class="lobby-mountain mountain-back"></div><div class="lobby-mountain mountain-front"></div><div class="war-banner banner-one">魏</div><div class="war-banner banner-two">蜀</div><div class="war-banner banner-three">吴</div><span class="art-caption">一役之间，风云再起</span></div></section>
    ${resume?`<section class="lobby-resume"><div><span class="live-dot"></span><b>${resume.name}</b><span>${resume.stage}</span></div><button class="button secondary" data-action="continue-history" ${resume.invalid?'disabled':''}>${resume.invalid?'请重新开始':resume.finished?'查看战报':'继续战役'} →</button></section>`:''}
    <section class="lobby-selection" aria-labelledby="battle-selection-title"><div class="lobby-section-title"><h2 id="battle-selection-title">选择战役</h2><span>九场独立战役 · 全部开放</span></div><div class="campaign-tabs" aria-label="战役类别"><button data-action="campaign-category" data-category="historical" class="${s.historical?'active':''}" aria-pressed="${s.historical}">历史战役 <small>4</small></button><button data-action="campaign-category" data-category="tactical" class="${!s.historical?'active':''}" aria-pressed="${!s.historical}">演义推演 <small>5</small></button></div><div class="lobby-battles"><div class="historical-list">${catalogue.map(c=>`<button class="historical-card ${c.id===s.id?'selected':''}" data-action="select-history" data-scenario="${c.id}" aria-pressed="${c.id===s.id}"><span class="chapter">${c.chapter}</span><span class="historical-card-copy"><small>${era(c)} · ${c.kind}</small><strong>${c.name}</strong><span>${c.subtitle}</span></span><span class="history-difficulty">${c.difficulty}<small>${c.feature}</small></span></button>`).join('')}</div>
    <article class="historical-detail" aria-label="${s.name}战役简报"><div class="eyebrow">${s.kind} · ${s.feature}</div><h2>${s.name}<small>${era(s)}</small></h2><p class="historical-intro">${s.description}</p><div class="historical-armies"><section><h3>你将指挥 · ${s.ownName}<small>${scenarioTroops(s,0).toLocaleString('zh-CN')} 人 · Lv.${s.level}</small></h3><div class="historical-roster">${roster(s.ownTeam,0)}</div></section><section><h3>对阵 · ${s.enemyName}<small>${scenarioTroops(s,1).toLocaleString('zh-CN')} 人 · Lv.${s.enemyLevel}</small></h3><div class="historical-roster">${roster(s.enemyTeam,1)}</div></section></div>${s.waves.length?`<p class="history-waves">敌军首发 ${Math.min(6,s.enemy)} 队；${s.waves.map(w=>`${w.tick} 步：${w.count} 队增援`).join('；')}。</p>`:''}<div class="historical-objective"><b>本役目标</b><p>${s.goal}</p></div><details class="historical-briefing"><summary>指挥提示与场景说明</summary><p>${s.briefing}</p><p>${s.history}</p></details><button class="button primary full history-launch" data-action="launch-history" data-scenario="${s.id}">出战 · 前往布阵 <span>→</span></button><small class="history-save-note">${resume?'开始新战役将替换当前战役进度。':'自动保存本场进度，随时回来继续。'}</small></article></div></section>
    <section class="lobby-howto"><span><b>01</b> 选择战役</span><i>→</i><span><b>02</b> 布阵 · 配置战法</span><i>→</i><span><b>03</b> 开战 · 暂停下令</span><i>→</i><span><b>04</b> 战报 · 重试</span></section>
    <footer class="lobby-footer"><p>历史战役经过玩法缩编；演义推演为虚构对局。每将显示实际兵力与带兵上限，胜负由实战决定。</p><div><button class="text-button" data-action="scenarios">演武试炼</button><button class="text-button" data-action="strategy">天下战略 <small>内政 · 行军 · 战役</small></button></div></footer>
  </main>`;
}
