import {DIPLOMACY_DIRECTIONS as DIRECTIONS,DIPLOMACY_GOALS as GOALS,DIPLOMACY_ACTIONS as ACTIONS,DIPLOMACY_STAT_NAMES as STATS} from './data/design/diplomacy-rules.mjs';
import {lordCity,diplomaticOfficerCandidates,evaluateDiplomaticProposal} from './diplomacy.mjs';
import {factionsHostile,factionsAllied} from './diplomacy-relations.mjs';
import {playerFaction} from './player-faction.mjs';
import {FACTIONS} from './engine.mjs';
import {OFFICER_BY_ID} from './officer-catalog.mjs';
import {mapNode} from './map-node-data.mjs';
import {strategicOrderLabel} from './strategic-orders.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Math.floor(n||0).toLocaleString('zh-CN');
const statuses={outbound:'出使中',negotiating:'谈判中',pending:'待批准',approved:'已批准，待签署',signed:'履约中',completed:'已完成',rejected:'未接受',expired:'已到期',cancelled:'已取消',failed:'履约中止',waiting:'待执行',active:'生效中',done:'已完成'};
export function diplomaticClauseText(s,c){
 const target=c.cityId?mapNode(s,c.cityId)?.name:c.targetId?mapNode(s,c.targetId)?.name:'';
 if(['gold','grain','manpower'].includes(c.kind))return `${ACTIONS[c.kind]} ${fmt(c.amount)}${c.deferred?`（签署后第${c.dueOffset}天偿付）`:c.milestone?'（援军抵达后支付）':''}`;
 if(c.kind==='city'||c.kind==='spoils')return `${ACTIONS[c.kind]} · ${target}`;
 if(c.kind==='prisoner')return '释放俘虏 · '+OFFICER_BY_ID[c.officerId]?.name;
 if(c.kind==='deploy')return `${c.task==='defend'?'防守':'出兵'}${target} · ${c.officerIds.length}队／${fmt(c.troops)}人 · 第${c.deadline}天前抵达`;
 if(c.kind==='declare')return '向'+FACTIONS[c.enemy]?.name+'宣战';
 if(c.kind==='restrictAid')return '不向'+FACTIONS[c.enemy]?.name+'提供军事支援';
 if(c.kind==='intelligence')return '共享'+c.information.length+'项已知情报';
 if(c.kind==='supply')return `君主城补给 · 累计${fmt(c.amount)}粮`;
 if(c.kind==='withdraw')return `军团${c.armyId}实际撤往${target}`;
 if(c.kind==='terminate')return `终止契约${c.contractId}，已发生债务继续结算`;
 return `${ACTIONS[c.kind]}${target?' · '+target:''}${c.duration?' · '+c.duration+'天':''}${c.quota?' · 总额度'+fmt(c.quota)+'粮 · '+c.unitPrice+'金／粮':''}${c.troopCap?' · 上限'+fmt(c.troopCap)+'人':''}`;
}
export function diplomaticProposalMarkup(s,p,{buttons=true}={}){
 const own=playerFaction(s),other=p.factions.find(f=>f!==own),assessment=evaluateDiplomaticProposal(s,p,own),action=p.status==='pending'&&buttons;
 const side=f=>p.clauses.filter(c=>c.from===f).map(c=>`<li>${esc(diplomaticClauseText(s,c))}${c.after?.length?'<small>待前置交付完成后生效</small>':''}${c.status?`<small>${statuses[c.status]||c.status}${c.amount?' · '+fmt(c.delivered)+' / '+fmt(c.amount):''}${c.untilDay?' · 至第'+c.untilDay+'天':''}${c.overdue?' · 债务逾期':''}</small>`:''}${c.cityId?`<button class="dispatch-link" data-action="campaign-info-detail" data-kind="city" data-id="${esc(c.cityId)}">查看城市</button>`:''}${c.officerId?`<button class="dispatch-link" data-action="campaign-info-detail" data-kind="officer" data-id="${esc(c.officerId)}">查看武将</button>`:''}${c.armyId?`<button class="dispatch-link" data-action="campaign-info-detail" data-kind="army" data-id="${esc(c.armyId)}">查看军团</button>`:''}</li>`).join('');
 return `<article class="diplomatic-proposal ${p.status==='pending'?'needs-approval':''}" data-diplomatic-proposal="${p.id}"><header><h3>${esc(GOALS[p.goal])} · ${esc(FACTIONS[other].name)}</h3><b>${p.status==='signed'&&p.fulfilledDay?'交付完成 · 约定有效':statuses[p.status]}</b></header><p class="diplomatic-officer">${OFFICER_BY_ID[p.officerId]?`<span class="diplomatic-officer-art" data-art-portrait="${esc(p.officerId)}" data-art-scene="diplomacy"><span>${esc(OFFICER_BY_ID[p.officerId].name.slice(-1))}</span></span>`:''}执行武将：${esc(OFFICER_BY_ID[p.officerId]?.name)} · 第${p.createdDay}天开始 · 方案${p.version}</p><div class="diplomatic-terms"><section><h4>我方给予</h4><p>收支城：${esc(mapNode(s,p.sites[own])?.name)}</p><ul>${side(own)||'<li>无约定支出</li>'}</ul></section><section><h4>对方给予</h4><p>收支城：${esc(mapNode(s,p.sites[other])?.name)}</p><ul>${side(other)||'<li>无约定对价</li>'}</ul></section></div><p>${esc(p.failure||assessment.reason)}。${p.status==='pending'?'批准前不付款、不交接、不改变条约与战争。':''}</p>${action?`<p>最迟第${p.expiresDay}天决定；过期不会自动接受。</p><div class="diplomatic-decisions"><button class="button primary" data-action="diplomacy-approve" data-proposal="${p.id}" data-version="${p.version}">批准</button><button class="button secondary" data-action="diplomacy-renegotiate" data-proposal="${p.id}">继续交涉</button><button class="button secondary" data-action="diplomacy-reject" data-proposal="${p.id}">否决</button></div>`:''}</article>`;
}
export function diplomacyMarkup(s){
 const own=playerFaction(s),d=s.campaign.diplomacy,policy=d.policies[own],c=lordCity(s,own),editable=s.campaign.phase==='planning'&&!s.finished,pending=d.proposals.filter(p=>p.factions.includes(own)&&['pending','approved'].includes(p.status));
 const relations=Object.keys(d.policies).filter(f=>f!==own&&s.cities.some(c=>c.owner===f)).map(f=>`<tr><td>${esc(FACTIONS[f].name)}</td><td>${esc(lordCity(s,f)?.name||'君主未驻城')}</td><td>${factionsAllied(s,own,f)?'同盟':factionsHostile(s,own,f)?'交战':'和平'}</td><td>${d.relations[[own,f].sort().join(':')]||0}</td><td>${d.credit[f]??100}</td></tr>`).join('');
 const directions=Object.entries(DIRECTIONS).map(([key,def])=>{const assigned=d.assignments.filter(a=>a.faction===own&&a.direction===key),candidates=diplomaticOfficerCandidates(s,own,key);return `<section class="diplomatic-direction"><h3>${def.name} · ${STATS[def.stat]}</h3>${assigned.map(a=>{const u=OFFICER_BY_ID[a.officerId],p=[...d.proposals,...d.contracts].find(p=>p.id===a.projectId);return `<p><button class="personnel-name" data-action="campaign-info-detail" data-kind="officer" data-id="${a.officerId}">${esc(u.name)}</button> · ${p?statuses[p.status]:esc(a.waiting)} <button class="button secondary" data-action="diplomacy-dismiss" data-officer="${a.officerId}" ${editable?'':'disabled'}>召回</button></p>`;}).join('')||'<p>未委任负责人</p>'}<label class="strategy-field">人选<select id="diplomacy-officer-${key}" ${editable?'':'disabled'}><option value="">请选择武将</option>${candidates.map(o=>`<option value="${o.unit.id}">${esc(o.unit.name)} · ${STATS[def.stat]}${o.unit[def.stat]} · ${esc(mapNode(s,o.location)?.name)}${o.work?.action?' · 内政办理中':''}</option>`).join('')}</select></label><button class="button secondary" data-action="diplomacy-assign" data-direction="${key}" ${editable?'':'disabled'}>委任</button></section>`;}).join('');
 const projects=d.proposals.filter(p=>p.factions.includes(own)&&!['pending','approved'].includes(p.status));const contracts=d.contracts.filter(p=>p.factions.includes(own));
 const locked=d.contracts.flatMap(p=>p.escrow).filter(e=>e.faction===own&&e.kind==='gold').reduce((n,e)=>n+e.amount,0);
 const orders=d.orders.filter(q=>q.faction===own),after=orders.length?`<section class="strategy-ledger pending-orders"><h3>返城后安排 · ${orders.length}</h3>${orders.map(q=>`<article><div><b>${esc(strategicOrderLabel(s,q.command))}</b><small>第${q.requestedDay}天下令 · ${q.choice==='now'?'已召回，实际返城后执行':'办完外交并返城后执行'}</small><p>${q.officerIds.map(id=>esc(OFFICER_BY_ID[id]?.name)).join('、')}</p></div><button class="button secondary" data-action="diplomacy-cancel-order" data-order="${q.id}" ${editable?'':'disabled'}>取消安排</button></article>`).join('')}</section>`:'';
 return `<section class="diplomacy-panel"><h3>外交</h3><p>定大方向，由武将自主拟案与谈判。最终方案须批准，获批后自动履约。</p><p>君主城：<b>${esc(c?.name||'尚未驻己方城市')}</b>${c?' · 本城粮'+fmt(c.grain)+' · 预备兵'+fmt(c.manpower):' · 新资源交易等待驻城'} · 已锁定金${fmt(locked)}</p><div class="diplomatic-goals"><label class="strategy-field">大方向<select id="diplomacy-goal" ${editable?'':'disabled'}>${Object.entries(GOALS).map(([key,name])=>`<option value="${key}" ${policy.goal===key?'selected':''}>${name}</option>`).join('')}</select></label><label class="strategy-field">重点势力<select id="diplomacy-target" ${editable?'':'disabled'}><option value="">自主选择</option>${Object.keys(d.policies).filter(f=>f!==own&&s.cities.some(c=>c.owner===f)).map(f=>`<option value="${f}" ${policy.target===f?'selected':''}>${esc(FACTIONS[f].name)}</option>`).join('')}</select></label><button class="button secondary" data-action="diplomacy-goal" ${editable?'':'disabled'}>确认</button></div><details><summary>办事经费与资源底线</summary><p>办事费用按实际接洽和出行消耗。底线与预算用于后台评估，最终交易仍须批准。</p><div class="diplomatic-budgets">${[["feeBudget","每旬行资上限"],["goldReserve","留存金"],["grainReserve","君主城留存粮"],["manpowerReserve","君主城留存预备兵"]].map(([key,name])=>`<label class="strategy-field">${name}<input id="diplomacy-${key}" type="number" min="0" step="1" value="${policy[key]}" ${editable?"":"disabled"}></label>`).join("")}</div><button class="button secondary" data-action="diplomacy-budget" ${editable?"":"disabled"}>保存边界</button></details><div class="diplomatic-directions">${directions}</div>${after}<h3>待批准 · ${pending.length}</h3>${pending.map(p=>diplomaticProposalMarkup(s,p)).join('')||'<p class="strategy-muted">暂无最终方案。查看或确认奏报不代表批准。</p>'}<details ${contracts.length?'open':''}><summary>条约与履约 · ${contracts.length}</summary>${contracts.map(p=>diplomaticProposalMarkup(s,p,{buttons:false})).join('')||'<p>暂无条约。</p>'}</details><details><summary>接洽记录 · ${projects.length}</summary>${projects.map(p=>diplomaticProposalMarkup(s,p,{buttons:false})).join('')||'<p>暂无接洽。</p>'}</details><details><summary>各势力关系</summary><div class="personnel-table-wrap"><table class="personnel-table"><thead><tr><th>势力</th><th>君主驻城</th><th>关系</th><th>交好</th><th>履约信用</th></tr></thead><tbody>${relations}</tbody></table></div></details></section>`;
}
