import {NATIONAL_FACTIONS,NATIONAL_SCENARIOS,nationalScenario,nationalWorld,nationalRoster} from './national-scenarios.mjs';
import {OFFICER_BY_ID} from './officer-catalog.mjs';
const footer=`<footer class="lobby-footer"><p>目标：占领全部 87 处据点。据点尽失则败北。<br>新开局更新普通模式自动存档，手动存档保留。战役模式进度独立保存。</p><div><button class="button primary" data-action="load">读取存档</button><button class="text-button" data-action="settings">存档与设置</button></div></footer>`;
export function nationalLobby(resume,draft={}){
 const spec=nationalScenario(draft.scenarioId),choosingForce=draft.step==='faction'&&spec;
 const nav=`<header class="lobby-nav"><a class="lobby-brand" href="#" data-action="lobby"><span>君</span>三国 · 君临</a><span class="lobby-edition">普通模式 · ${choosingForce?'选择势力':'选择剧本'}</span><button class="text-button" data-action="${choosingForce?'national-back':'lobby'}">${choosingForce?'返回剧本选择':'返回模式选择'}</button></header><ol class="national-steps" aria-label="新游戏流程"><li ${!choosingForce?'aria-current="step"':''}>01 选择剧本</li><li ${choosingForce?'aria-current="step"':''}>02 选择势力</li><li>03 开始征程</li></ol>`;
 if(choosingForce){
  const world=nationalWorld(spec.id),roster=nationalRoster(spec.id,world.cities),selected=spec.factions.includes(draft.faction)?draft.faction:null;
  return `<main class="campaign-lobby national-lobby">${nav}<section class="national-intro"><div><span class="eyebrow">${spec.year} 年 · ${spec.era} · ${spec.name}</span><h1>择一势力，开创霸业</h1></div></section><section class="national-scenario-list national-faction-list" aria-label="选择势力">${spec.factions.map(f=>{
   const force=NATIONAL_FACTIONS[f],owned=world.cities.filter(c=>c.owner===f),people=roster.filter(o=>o.faction===f),notables=people.map(o=>OFFICER_BY_ID[o.id]).sort((a,b)=>Number(b.sourceId===force.leaderSourceId)-Number(a.sourceId===force.leaderSourceId)||b.leadership+b.intellect-a.leadership-a.intellect).slice(0,6);
   return `<article class="national-scenario-card ${selected===f?'selected':''}" style="--force-color:${force.color}"><span class="eyebrow">${spec.name} · ${selected===f?'已选择':'可选势力'}</span><h2>${force.name}</h2><div class="national-scenario-stats"><span>城池<b>${owned.filter(c=>c.kind==='city').length}</b></span><span>据点<b>${owned.length}</b></span><span>武将<b>${people.length}</b></span></div><p>主要领地：${owned.filter(c=>c.kind==='city').slice(0,5).map(c=>c.name).join('、')}</p><p>麾下人才：${notables.map(u=>u.name).join('、')}</p><button class="button ${selected===f?'primary':'secondary'} full" data-action="select-national-faction" data-faction="${f}" aria-pressed="${selected===f}">${selected===f?'已选择':'选择'}${force.name}</button></article>`;
  }).join('')}</section><section class="national-confirm"><div><b>${spec.name}${selected?' · '+NATIONAL_FACTIONS[selected].name+'势力':''}</b><p>${selected?'已选定剧本与势力，确认后进入天下大地图。':'请选择要执掌的势力。'}</p></div><button class="button primary" data-action="launch-national" ${selected?'':'disabled'}>开始游戏</button></section>${footer}</main>`;
 }
 return `<main class="campaign-lobby national-lobby">${nav}<section class="national-intro"><div><span class="eyebrow">九州烽烟 · 城郭关津</span><h1>择一时局，逐鹿天下</h1></div><div class="national-counts"><span><b>42</b>座城池</span><span><b>10</b>座关隘</span><span><b>35</b>处港口</span></div></section>${resume?`<section class="national-resume"><div><b>继续 · ${nationalScenario(resume.scenarioId)?.name||'天下征途'}</b><p>${NATIONAL_FACTIONS[resume.playerFaction]?.name||'曹操'}势力 · 第 ${resume.day} 天</p></div><button class="button primary" data-action="continue-national">继续征程</button></section>`:''}<section class="national-scenario-list" aria-label="选择天下剧本">${NATIONAL_SCENARIOS.map((s,i)=>`<article class="national-scenario-card ${draft.scenarioId===s.id?'selected':''}"><div class="national-scenario-seal">${i?'群英':'官渡'}</div><span class="eyebrow">${s.year} 年 · ${s.era} · ${s.difficulty}</span><h2>${s.name}</h2><p>${s.description}</p><p class="national-forces">可选势力 · ${s.factions.map(f=>NATIONAL_FACTIONS[f].name).join(' / ')}</p><small>${s.note}</small><button class="button primary full" data-action="select-national-scenario" data-scenario="${s.id}">选择「${s.name}」 · 下一步</button></article>`).join('')}</section>${footer}</main>`;
}
