import {NATIONAL_MAP_COUNTS,NATIONAL_FACTIONS,NATIONAL_SCENARIOS,nationalScenario,nationalWorld,nationalRoster} from './national-scenarios.mjs';
import {OFFICER_BY_ID} from './officer-catalog.mjs';
import {geographyLabels} from './national-geography.mjs';
import {atlasOverviewMarkup} from './ancient-atlas-terrain.mjs';
import {citySizeName,cityMarkerShape} from './city-classification.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cityCounts=(()=>{const cities=nationalWorld(NATIONAL_SCENARIOS[0].id).cities;return {large:cities.filter(c=>c.citySize==='large').length,small:cities.filter(c=>c.citySize==='small').length};})();
const leader=f=>Object.values(OFFICER_BY_ID).find(u=>u.sourceId===NATIONAL_FACTIONS[f].leaderSourceId)||Object.values(OFFICER_BY_ID).find(u=>u.name===NATIONAL_FACTIONS[f].name);
function map(spec,selected){const w=nationalWorld(spec.id);return `<svg class="selection-map" viewBox="0 0 1024 1024" aria-label="${esc(spec.name)}势力据点分布">${atlasOverviewMarkup('selection-land')}${geographyLabels()}${w.cities.filter(c=>c.kind==='city').map(c=>{const f=NATIONAL_FACTIONS[c.owner],enabled=spec.factions.includes(c.owner);return `<g ${enabled?`role="button" tabindex="0" data-action="select-national-faction" data-faction="${c.owner}" aria-label="选择${f.name}，${c.name}，${citySizeName(c)}"`:''} opacity="${selected&&selected!==c.owner?'.45':'1'}"><g data-selection-city="${c.id}" data-city-size="${c.citySize}" transform="translate(${c.x} ${c.y})">${cityMarkerShape(c,c.citySize==='small'?(selected===c.owner?13:9):(selected===c.owner?19:13),`fill="${f?.color||'#777061'}" stroke="${selected===c.owner?'#ffe598':'#c6b891'}" stroke-width="3"`)}</g><text x="${c.x+23}" y="${c.y+6}" fill="#fff0cc" font-size="18" paint-order="stroke" stroke="#302b24" stroke-width="3">${c.name}</text></g>`;}).join('')}</svg>`;}
const footer=`<footer class="selection-footer"><span>一统天下 · 占领全部 ${NATIONAL_MAP_COUNTS.city} 座城市</span><button class="text-button" data-action="load">读取存档</button><button class="text-button" data-action="settings">设置</button></footer>`;
export function nationalLobby(resume,draft={}){
 const spec=nationalScenario(draft.scenarioId)||NATIONAL_SCENARIOS[0],forceStep=draft.step==='faction',selected=spec.factions.includes(draft.faction)?draft.faction:null;
 const nav=`<header class="selection-header"><h1>${forceStep?'选择势力':'选择剧本'}</h1><span>${forceStep?`${spec.year} 年 · ${spec.era} · ${spec.name}`:'汉末风云 · 群雄逐鹿'}</span><button class="text-button" data-action="${forceStep?'national-back':'lobby'}">${forceStep?'返回剧本':'返回'}</button></header>`;
 if(!forceStep)return `<main class="campaign-lobby national-lobby selection-screen">${nav}<section class="scenario-stage"><div class="scenario-scroll"><p class="eyebrow">第一步 · 选择天下时局</p>${NATIONAL_SCENARIOS.map(s=>`<button class="scenario-ribbon" data-action="select-national-scenario" data-scenario="${s.id}"><span>${s.kind==='fictional'?'架空':'历史改编'}</span><strong>${s.year} 年　${s.name}</strong><small>${s.era} · ${s.difficulty}</small><p>${s.description}</p><em>选择剧本　→</em></button>`).join('')}${resume?`<button class="scenario-continue" data-action="continue-national">继续征程 · ${esc(nationalScenario(resume.scenarioId)?.name)}<small>${resume.allAI?'全 AI 观战 · ':''}${esc(NATIONAL_FACTIONS[resume.playerFaction]?.name)}势力 · 第 ${resume.day} 天</small></button>`:''}</div><div class="scenario-landscape">${map(spec,null)}<div class="scenario-portraits">${spec.factions.slice(0,3).map(f=>`<div data-art-portrait="${leader(f)?.id||''}" data-art-scene="detail"><span>${NATIONAL_FACTIONS[f].name}</span></div>`).join('')}</div><aside><h2>九州烽烟，谁主沉浮</h2><p>选择剧本后，在全国版图中挑选要执掌的势力。</p><small>${cityCounts.large} 大城 · ${cityCounts.small} 小城 · ${NATIONAL_MAP_COUNTS.gate} 关隘 · ${NATIONAL_MAP_COUNTS.port} 港口</small></aside></div></section>${footer}</main>`;
 const observer=!!draft.allAI;
 const world=nationalWorld(spec.id),roster=nationalRoster(spec.id,world.cities),f=selected&&NATIONAL_FACTIONS[selected],u=selected&&leader(selected),owned=world.cities.filter(c=>c.owner===selected),people=roster.filter(o=>o.faction===selected);
 return `<main class="campaign-lobby national-lobby selection-screen">${nav}<section class="force-stage"><div class="force-showcase"><div class="ruler-portrait" data-art-portrait="${u?.id||''}" data-art-scene="detail"><span>${f?.name||'待君入局'}</span></div><div class="force-summary"><span class="eyebrow">${selected?(observer?'观战视角':'所选势力'):'第二步 · 选择势力'}</span><h2>${f?.name||(observer?'请选择初始观战视角':'请选择要执掌的君主')}</h2>${selected?`<div class="force-numbers"><span>城池<b>${owned.filter(c=>c.kind==='city').length}</b></span><span>据点<b>${owned.length}</b></span><span>武将<b>${people.length}</b></span></div><p>主要领地　${owned.filter(c=>c.kind==='city').map(c=>c.name).join('、')}</p><p>麾下武将　${people.slice(0,8).map(o=>OFFICER_BY_ID[o.id]?.name).filter(Boolean).join('、')}</p>`:'<p>点击下方君主头像，或点击地图中的势力据点。</p>'}</div></div><div class="force-map">${map(spec,selected)}<small>□ 大城　○ 小城 · 金边标出所选势力</small></div></section><nav class="ruler-strip" aria-label="选择势力">${spec.factions.map(id=>`<button data-action="select-national-faction" data-faction="${id}" aria-label="选择${NATIONAL_FACTIONS[id].name}" aria-pressed="${selected===id}" style="--force-color:${NATIONAL_FACTIONS[id].color}"><i data-art-portrait="${leader(id)?.id||''}"><span>${NATIONAL_FACTIONS[id].short}</span></i><b>${NATIONAL_FACTIONS[id].name}</b></button>`).join('')}</nav><section class="selection-confirm"><div><button class="button secondary" data-action="national-control" aria-pressed="${observer}">${observer?'全 AI 观战':'玩家执掌'}</button><p>${observer?'所有势力均由 AI 操控；所选势力仅为观察视角，可随时切换。':'所选势力由玩家执掌，其他势力由 AI 操控。'}</p></div><p>${spec.note}</p><button class="button primary" data-action="launch-national" ${selected?'':'disabled'}>${observer?'开始观战':'开始'}</button><button class="button secondary" data-action="national-back">返回</button></section>${footer}</main>`;
}
