import {gateDurability} from './building-durability.mjs';
import {mapNode} from './map-node-data.mjs';
import {scoutCandidates,scoutTargets,scoutRoute,scoutAssignments,scoutingDurationRange} from './scouting.mjs';
import {scoutOperator,scoutStatus} from './scouting-state.mjs';
import {roadCost} from './road-metrics.mjs';
import {MOVEMENT_RULES} from './data/design/movement-rules.mjs';
import {NATIONAL_FACTIONS as FACTIONS} from './national-scenarios.mjs';
import {TROOP_DESIGNS} from './data/design/troops.mjs';
import {playerFaction} from './player-faction.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>Number.isFinite(v)?Math.floor(v).toLocaleString('zh-CN'):'—';
export function scoutingMarkup(s,selection={}){
 const faction=playerFaction(s),cities=s.cities.filter(c=>c.owner===faction),city=cities.find(c=>c.id===selection.city),candidates=city?scoutCandidates(s,city.id):[],officer=candidates.find(o=>o.unit.id===selection.officer),range=scoutingDurationRange(officer?.unit.intellect);
 const targets=officer?scoutTargets(s,city.id):[],target=targets.find(n=>n.id===selection.target),path=city&&target&&scoutRoute(s,city.id,target.id),cost=path?.reduce((sum,id,index)=>sum+roadCost(s,index?path[index-1]:city.id,id),0),tasks=scoutAssignments(s).filter(t=>t.faction===faction);
 const besieged=city&&s.campaign.battles.some(b=>!b.settled&&b.kind==='siege'&&b.cityId===city.id),allowed=s.campaign.phase==='planning'&&!s.finished&&!besieged&&city&&officer&&path?.length;
 return `<section class="scouting-workbench"><p class="muted">负责人留在城内工作，由模拟斥候沿道路侦察。遇到据点、军团即获得情报并点亮附近视野；智力越高，视野持续越久，到期恢复灰雾。</p><div class="scout-fields"><label>1 · 派出城市<select id="scout-city"><option value="">选择派出城市</option>${cities.map(c=>`<option value="${c.id}" ${city?.id===c.id?'selected':''}>${esc(c.name)} · 可指派 ${scoutCandidates(s,c.id).length} 人</option>`).join('')}</select></label><label>2 · 本城负责武将<select id="scout-officer" ${city&&candidates.length?'':'disabled'}><option value="">${!city?'先选择城市':!candidates.length?'本城没有可指派武将':'选择本城武将'}</option>${candidates.map(o=>`<option value="${esc(o.unit.id)}" ${officer?.unit.id===o.unit.id?'selected':''}>${esc(o.unit.name)} · 智力 ${o.unit.intellect}</option>`).join('')}</select></label><label>3 · 周边侦察终点<select id="scout-target" ${officer?'':'disabled'}><option value="">${officer?'选择周边据点或相邻城市':'先选择负责武将'}</option>${targets.map(n=>`<option value="${n.id}" ${target?.id===n.id?'selected':''}>${esc(n.province||'')} · ${esc(n.name)}</option>`).join('')}</select></label></div><p class="muted">仅可侦察本城周边据点和相邻城市，不能穿过其它城市继续侦察。</p>${besieged?'<p>本城正在被围攻，暂时不能指派侦察。</p>':''}${city&&!candidates.length?'<p>负责人须实际在本城，未任职且没有其它工作或等待命令；在城部队的武将也可负责。</p>':''}${officer?`<p class="scout-duration">${esc(officer.unit.name)} · 智力 ${officer.unit.intellect} · 每处视野随机持续 ${range.min}–${range.max} 天</p>`:''}${path?.length?`<div class="scout-route"><b>斥候路线</b><p>${[city.id,...path].map(id=>esc(mapNode(s,id).name)).join(' → ')}</p><p>预计 ${Math.ceil(cost/MOVEMENT_RULES.personnel.light)} 天抵达 · 负责武将仍在${esc(city.name)}</p></div>`:''}<button class="button primary" data-action="scout-dispatch" data-city="${city?.id||''}" data-officer="${officer?.unit.id||''}" data-target="${target?.id||''}" ${allowed?'':'disabled'}>指派侦察</button><h3>侦察工作 · ${tasks.length} 项</h3><div class="scout-missions">${tasks.map(t=>{const o=scoutOperator(s,t);return `<article><b>负责人：${esc(o?.unit.name)} · 在${esc(mapNode(s,t.homeCity).name)}工作</b><span>${scoutStatus(t)} · ${esc(mapNode(s,t.location).name)}${t.route.length?' → '+esc(mapNode(s,t.route[0]).name):''}</span><small class="scout-duration">智力 ${o?.unit.intellect} · 每处视野随机持续 ${scoutingDurationRange(o?.unit.intellect).min}–${scoutingDurationRange(o?.unit.intellect).max} 天</small><small>侦察终点：${esc(mapNode(s,t.targetCity).name)} · 已获 ${t.contacts.length} 项情报</small><button class="button secondary" data-action="campaign-info-detail" data-kind="officer" data-id="${esc(t.officerId)}">负责人详情</button><button class="button secondary" data-action="scout-recall" data-officer="${esc(t.officerId)}">停止侦察</button><details class="scout-contact-list"><summary>沿路情报 · ${t.contacts.length} 项</summary>${t.contacts.map(c=>`<p>${esc(c.name)} · ${c.kind==='army'?'军团':'据点'} · 第 ${c.report.day} 天 <button class="personnel-name" data-action="scout-report" data-task="${t.id}" data-key="${esc(c.key)}">查看情报 ↗</button></p>`).join('')||'<p>斥候尚未遇到其它据点或军团。</p>'}</details></article>`;}).join('')||'<p>尚未指派侦察负责人。</p>'}</div></section>`;
}
export function scoutingReportMarkup(s,selection={}){
 const t=scoutAssignments(s).find(t=>t.id===selection.task&&t.faction===playerFaction(s)),c=t?.contacts.find(c=>c.key===selection.key);
 if(!c)return {title:'侦察情报',body:'<p>该侦察记录已结束。</p>'};
 const d=c.report.data,fields=c.kind==='city'?[['势力',FACTIONS[d.owner]?.name||'无主'],['本城金',number(d.gold)],['存粮',number(d.grain)],['预备兵',number(d.manpower)],['城门耐久',number(gateDurability(d).hp)],['驻城士兵',number(d.units.reduce((n,u)=>n+u.troops,0))]]:c.kind==='army'?[['势力',FACTIONS[d.faction]?.name||'无主'],['兵力',number(d.units.reduce((n,u)=>n+u.troops,0))],['士气',number(d.morale)],['携粮',number(d.supply)],['观察位置',d.travel?mapNode(s,d.travel.from).name+' → '+mapNode(s,d.travel.to).name:mapNode(s,d.location).name]]:[['类型',({gate:'关卡',port:'港口',junction:'路口'})[d.kind]],['地域',d.province]];
 return {title:c.name,body:`<p>第 ${c.report.day} 天的侦察报告 · 负责人${esc(scoutOperator(s,t)?.unit.name)}在${esc(mapNode(s,t.homeCity).name)}工作。</p><dl class="info-fields">${fields.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>${d.units?`<h3>${c.kind==='army'?'所属部队':'驻城部队'}</h3><div class="personnel-table-wrap"><table><thead><tr><th>武将</th><th>兵种</th><th>士兵</th></tr></thead><tbody>${d.units.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(TROOP_DESIGNS[u.type]?.name)}</td><td>${number(u.troops)}</td></tr>`).join('')||'<tr><td colspan="3">未发现驻军</td></tr>'}</tbody></table></div>`:''}`};
}
