import {domesticReference,buildingReference} from './domestic-reference.mjs';
import {abilityButton} from './ability-reference.mjs';
import {detailLink} from './ui-detail-table.mjs';
import {mapObjectMenu} from './map-object-menu.mjs';
import {mapNode} from './road-network.mjs';
import {grainCapacity} from './domestic.mjs';
import {DIRECTION_STATS} from './domestic-designs.mjs';
import {DOMESTIC_STAT_LABELS} from './domestic-cooperation.mjs';
import {contributionText} from './progression.mjs';
import {playerFaction} from './player-faction.mjs';
import {sortRows,sortHeader} from './list-sort.mjs';
import {armyMapMarkers} from './strategic-army-markers.mjs';
import {infoLink} from './campaign-info.mjs';
import {pendingOrdersMarkup} from './strategic-order-view.mjs';
import {armyWaitingOrder} from './strategic-orders.mjs';
import {campaignRoads,roadCost,renderRoads,renderMarchRoute,renderSupplyRoute} from './strategic-movement.mjs';
import {cityPersonnel} from './city-personnel.mjs';
import {campaignOfficers} from './strategic-roster.mjs';
import {nationalScenario,campaignDate} from './national-scenarios.mjs';
import {CAMPAIGN,PROJECTS,calendar,isPlanning,activeBattles,armyBattle,armyPosition,armyActionPoints,liveSoldiers,dailyConsumption,cityIncome,canEditArmy,readDailySnapshot,supplyConnection} from './strategic-campaign.mjs';
import {FACTIONS,TROOPS} from './engine.mjs';
import {BATTLE_TERRAINS} from './battlefield.mjs';
import {strategicArtMap} from './art-strategic-map.mjs';
import {projectCost,reliefAmount,governorSkillList} from './strategic-campaign.mjs';
import {passiveList,PASSIVES} from './passives.mjs';
import {DIRECTIONS,BUILDINGS,ACTIONS,TECHS,actionName,assignmentFor,cityMilitary,siegeOpening,canTrain} from './domestic.mjs';
import {OFFICER_BY_ID} from './officer-catalog.mjs';
import {talentSummary} from './talent-lifecycle.mjs';
import {TALENT_REASONS} from './talent-core.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.round(n).toLocaleString('zh-CN');
const button=(action,label,disabled=false,extra='')=>`<button class="button secondary" data-action="${action}" ${disabled?'disabled':''} ${extra}>${label}</button>`;
export function campaignBattleBar(s){const d=calendar(s),r=s.campaign.battles.find(r=>r.id===s.campaign.focusId);return `<div id="campaign-battle-bar" class="campaign-battle-bar"><span><b>第 ${d.turn} 旬 · 第 ${d.dayInTurn} 天</b>　世界第 ${d.day} 天 · 交战第 ${d.day-(r?.startedDay||d.day)+1} 天 / ${CAMPAIGN.maxBattleDays} 天 · 日内 ${s.campaign.stepInDay}/${CAMPAIGN.stepsPerDay}</span><div>${button('campaign-day','推进本日')}${button('campaign-map','交还委托 · 返回大地图')}</div></div>`;}
export function strategicView(s,ui){
  const d=calendar(s),planning=isPlanning(s),a=s.armies.find(a=>a.id===ui.army)||s.armies.find(a=>a.faction===playerFaction(s)),selected=s.cities.find(c=>c.id===ui.city)||s.cities.find(c=>c.owner===playerFaction(s))||s.cities[0];
  const live=activeBattles(s),pending=live.filter(r=>r.awaiting),tabs={city:'城池内政',army:'军团调度',officers:'武将与人事',battles:'战役与快照'};
  const tab=ui.strategyTab||'city';
  return `<main class="campaign strategy-page strategy-map-first ${ui.mapPanelOpen?'panel-open':''} ${ui.mapDirectoryOpen?'directory-open':''}"><header class="strategy-heading"><div><span class="eyebrow">军国大事 · 旬回合筹划 / 逐日执行</span><h1>${nationalScenario(s.campaign.scenarioId)?.name||'天下大势'}</h1><p>${FACTIONS[playerFaction(s)].name}势力 · ${campaignDate(s)} · 一旬十天，诸军共享日历。占领全部 ${s.cities.length} 处据点。</p></div><div>${button('campaign-info','天下情报')}${button('lobby','模式首页')}${button('settings','存档与设置')}${button('journal','天下纪事')}</div></header>
  <section class="strategy-clock"><div><strong>第 ${d.turn} 旬</strong><span>世界第 ${d.day} 天 · 本旬第 ${d.dayInTurn} 天</span></div><div class="day-track">${Array.from({length:10},(_,i)=>`<i class="${i+1<d.dayInTurn?'done':i+1===d.dayInTurn?'current':''}">${i+1}</i>`).join('')}</div><div><b>${planning?'战略筹划 · 全局暂停':ui.paused?'世界已暂停':'执行中'}</b><small>${live.length} 处交战 · 府库 ${fmt(s.gold)} 金 · 城内粮草 ${fmt(s.grain)}</small></div><div class="strategy-clock-actions">${planning?`<button class="button primary" data-action="campaign-begin" ${s.finished?'disabled':''}>进行 · 执行本旬</button>`:button('campaign-run',ui.paused?'继续进行':'暂停世界',pending.length>0||!!s.finished)}${button('campaign-day','推进一天',planning||pending.length>0||!!s.finished)}</div></section>
  <div class="strategy-notice" role="status">${esc(s.finished?(s.finished==='victory'?'天下归一，本局胜利。':'城池尽失，本局结束。'):s.campaign.lastNotice)}</div>
  ${pending.map(r=>`<section class="encounter-callout"><div><b>新遭遇 · ${esc(r.name)}</b><span>第 ${r.startedDay} 天 · ${BATTLE_TERRAINS[r.battle.terrain]} · ${r.battle.sides.map(x=>fmt(x.units.reduce((n,u)=>n+u.hp,0))+' 人').join(' 对 ')}</span></div><div>${r.kind==='siege'&&s.cities.find(c=>c.id===r.cityId)?.owner===playerFaction(s)?button('campaign-defense-prepare','临时编制守城部队',false,`data-battle="${r.id}"`):''}${button('campaign-prepare','查看敌情 · 战前军议',false,`data-battle="${r.id}"`)}</div></section>`).join('')}
  <div class="strategy-layout">${cityDirectory(s,selected)}<section class="strategy-map-panel"><div class="strategy-map-caption"><b>${s.campaign.scenarioId?'当前操作区域':'中原战区'}</b><span><i class="legend-own"></i>己方　<i class="legend-enemy"></i>敌军　<span class="supply-key">实线：道路 · 虚线：横向小路 · 蓝线：粮道</span></span></div><nav class="map-workspace-actions" aria-label="地图操作"><button data-action="map-directory-toggle" aria-expanded="${!!ui.mapDirectoryOpen}">管辖据点</button><button data-action="map-panel-toggle" aria-expanded="${!!ui.mapPanelOpen}">${ui.mapPanelOpen?'收起信息':'所选对象'}</button><span>点选查看 · 拖动巡视 · 滚轮缩放</span></nav>${map(s,ui,a)}<div class="strategy-map-caption"><span>点选城市 / 军团查看；选择调动后规划路线。</span><b>${s.armies.filter(a=>a.route.length&&!armyBattle(s,a.id)).length} 支军团行军中</b></div></section>
  <aside class="strategy-panel"><button class="map-panel-close" data-action="map-panel-toggle">收起面板 ×</button><nav class="strategy-tabs">${Object.entries(tabs).map(([key,label])=>`<button data-action="campaign-tab" data-tab="${key}" class="${tab===key?'active':''}">${label}</button>`).join('')}</nav>${tab==='city'?cityPanel(s,selected,ui):tab==='army'?armyPanel(s,a):tab==='officers'?officerPanel(s,selected):battlesPanel(s,planning)}</aside></div>
  ${mapObjectMenu(s,ui.mapObject)}${pendingOrdersMarkup(s)}<details class="strategy-ledger domestic-events"><summary>内政纪事 · 行动与真实收支</summary>${s.campaign.domestic.events.filter(e=>e.cityId===selected.id&&e.faction===playerFaction(s)).slice(0,16).map(e=>`<p><small>第${e.day}天 · ${esc(({assignment:'委任',start:'开始',complete:'完成',failure:'未达预期',cancel:'中止',pause:'暂停',resume:'恢复',event:'事件',cooperation:'协作','order-wait':'后续命令','order-done':'命令执行','order-cancel':'取消等待'})[e.phase])}</small> ${esc(e.text)}</p>`).join('')||'<p>委任负责人后，将在此记录每项行动的开始与结果。</p>'}</details>
  ${s.campaign.turnReports.length?`<details class="strategy-ledger"><summary>上旬收支与建设 · 第 ${s.campaign.turnReports[0].turn} 旬</summary>${s.campaign.turnReports[0].items.map(x=>`<p>${esc(x)}</p>`).join('')}</details>`:''}
  ${strategicAIMarkup(s)}
  <details class="strategy-ledger"><summary>人员动向 · 被俘与赎回</summary>${s.campaign.domestic.people.filter(p=>p.fate&&p.status==='CAPTIVE'&&(p.fate.originalFaction===playerFaction(s)||p.fate.captor===playerFaction(s))).map(p=>`<p>${infoLink('officer',p.id,p.unit.name)} · ${p.custody?'押送途中':'被俘'} · ${FACTIONS[p.fate.captor].name}</p>`).join('')||'<p>暂无相关俘虏。</p>'}${s.campaign.personnelEvents.slice(0,16).map(e=>`<p>第 ${e.day} 天 · ${esc(e.text)}</p>`).join('')}</details><footer class="strategy-footer">内政与军令在旬首安排。战役中可随时暂停下令，跨旬自动返回战略筹划。后台按日仿真，历史快照只读。</footer></main>`;
}
export function strategicAIMarkup(s){
 if(!s.campaign.ai)return '';
 const phase={prepare:'筹备',assemble:'集结',attack:'出征交战',consolidate:'巩固守备',complete:'已完成',cancelled:'已取消'},ai=s.campaign.ai;
 const plans=ai.plans.filter(p=>!['complete','cancelled'].includes(p.phase)).map(p=>`<p><b>${esc(FACTIONS[p.faction]?.name)} · ${phase[p.phase]}</b> ${esc(s.cities.find(c=>c.id===p.staging)?.name)} → ${esc(s.cities.find(c=>c.id===p.target)?.name)}<br><small>${p.officerIds.length} 支部队 · ${esc(p.reason)}</small></p>`).join('');
 const recent=ai.decisions.slice(0,12).map(d=>`<p><small>第 ${d.day} 天 · ${esc(FACTIONS[d.faction]?.name)} · ${esc(d.name)}</small> ${esc(d.reason)}${d.target?' · '+esc(s.cities.find(c=>c.id===d.target)?.name):''}</p>`).join('');
 return `<details class="strategy-ledger faction-plans"><summary>诸侯动向 · 势力计划与调度</summary>${plans}${recent||'<p>执行本旬后可查看诸侯的筹备、行军、增援与运输动向。</p>'}</details>`;
}
export const commandMap=(s,ui,a)=>map(s,ui,a);
function map(s,ui,a){
  const artwork=strategicArtMap(s,ui,a);if(artwork)return artwork;
  const byId=id=>mapNode(s,id),selected=ui.city,line=a?supplyConnection(s,a):null;
  const legs=line?line.path.slice(1).map((id,i)=>[byId(line.path[i]),byId(id)]):[];
  if(line&&a.travel)legs.push([byId(a.location),armyPosition(s,a)]);
  const previous=ui.armyPositions||{};ui.armyPositions={};
  return `<svg class="strategy-world" viewBox="100 25 820 760" aria-label="中原军团与粮道地图"><defs><pattern id="strategy-grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="#899b85" stroke-opacity=".055"/></pattern></defs><rect x="100" y="25" width="820" height="760" fill="url(#strategy-grid)"/><path d="M150 175 Q280 130 400 220 T780 210 Q800 255 900 300" class="strategy-river"/><text x="610" y="208" class="river-label">黄 河</text><path d="M170 100l40-40 40 40m-30 0 45-60 45 60M150 410l35-50 35 50m-10 0 40-65 40 65" class="strategy-mountains"/>
  ${renderRoads(s)}
  ${renderMarchRoute(s,a)}
  ${renderSupplyRoute(s,a,line)}
  ${s.cities.map(c=>`<g data-city="${c.id}" tabindex="0" role="button" aria-label="${c.name}，${FACTIONS[c.owner].name}" class="strategy-city ${c.owner} ${selected===c.id?'selected':''}" transform="translate(${c.x} ${c.y})"><circle r="27"/><path d="M-14 11V-5h5v-9h5v7h8v-7h5v9h5v16Z"/><text y="48">${c.name}</text><text class="city-stock" y="64">粮 ${fmt(c.grain)}</text></g>`).join('')}
  ${armyMapMarkers(s,ui)}
  ${activeBattles(s).map(r=>`<g class="strategy-battle-marker" data-action="campaign-focus" data-battle="${r.id}" tabindex="0" role="button" aria-label="${esc(r.name)}" transform="translate(${r.point.x} ${r.point.y+22})"><circle r="15"/><text y="5">战</text></g>`).join('')}</svg>`;
}
function domesticDirections(s,c,officers,editable){
 return `<div class="domestic-directions">${Object.entries(DIRECTIONS).map(([direction,name])=>{
  const assignments=s.campaign.domestic.assignments.filter(a=>a.cityId===c.id&&a.direction===direction),record=s.campaign.domestic.cooperation[c.id+':'+direction];
  return `<article class="domestic-direction" data-direction="${direction}"><h3>${name} · ${DOMESTIC_STAT_LABELS[DIRECTION_STATS[direction]]}<small class="duty-badge ${assignments.length?'staffed':'vacant'}">${assignments.length?assignments.length+'人负责':'未委任'}</small></h3>
   ${assignments.map(a=>{const x=a.action,u=officers.find(o=>o.unit.id===a.officerId)?.unit;return `<div class="domestic-assignee" data-domestic-officer="${a.officerId}"><div class="domestic-assignee-heading"><button class="personnel-name" data-action="campaign-person-detail" data-officer="${a.officerId}">${esc(u?.name||OFFICER_BY_ID[a.officerId].name)} ↗</button>${button('domestic-dismiss','解除',!editable,`data-officer="${a.officerId}" aria-label="解除${esc(u?.name||OFFICER_BY_ID[a.officerId].name)}的${name}委任"`)}</div>${x?`${detailLink('事务说明',[{name:actionName(c,x.key),rows:[['办理人','',u?.name||OFFICER_BY_ID[a.officerId].name],['事务','',actionName(c,x.key)],['目标','',TECHS[x.targetId]?.name||OFFICER_BY_ID[x.targetId]?.name||c.name],['剩余时间','',Number(x.remaining.toFixed(2))+' 天'],['已付费用','',x.cost+' 金'],['成功把握','',Math.round(x.chance*100)+'%'],['进度','',x.paused?'围城暂停':'办理中']]}],actionName(c,x.key))}<span>剩余${Number(x.remaining.toFixed(2))}天 · 已付${x.cost}金 · 成功把握${Math.round(x.chance*100)}%${x.paused?' · 围城暂停':''}</span>${x.traitIds.length?`<small>事务特性：${x.traitIds.map(id=>abilityButton('trait',id,PASSIVES[id].name)).join(' ')}</small>`:''}`:`<p>${esc(a.waiting)}</p>`}</div>`;}).join('')}
   ${domesticReference(direction)}${button('campaign-pick','委任武将',!editable,`data-task="domestic" data-town="${c.id}" data-direction="${direction}"`)}
   ${record?detailLink('协作记录',[{name:name,rows:[['时间','','第'+record.turn+'旬'],['武将','',OFFICER_BY_ID[record.officerId].name+' · '+OFFICER_BY_ID[record.helperId].name],['事务','',actionName(c,record.actionKey)],['机会','',Math.round(record.chance*100)+'%'],['成果','',!record.success?'未触发':record.actual>0?(record.mode==='chance'?'成功把握':record.mode==='progress'?'施工进度（天）':'行动成果')+' +'+Number(record.actual.toFixed(3))+(record.mode==='chance'?'个百分点':''):'无额外成果'],['关系','',String(record.relationGain||0)]]}],'协作记录'):''}<small>${Object.entries(BUILDINGS).filter(([,b])=>b.direction===direction).map(([key,b])=>buildingReference(c,key)).join(' · ')}</small></article>`;
 }).join('')}</div>`;
}
export function cityDomesticMarkup(s,id){
 const c=s.cities.find(c=>c.id===id);if(!c)return '<p>据点已不存在。</p>';
 const income=cityIncome(s,c),own=c.owner===playerFaction(s);
 return `<section class="domestic-workbench"><header><h3>${esc(c.name)} · 内政</h3><p>府库 ${fmt(s.gold)} 金 · 本城粮草 ${fmt(c.grain)} · 预备兵 ${fmt(c.manpower)}</p><p>每旬预计：${fmt(income.gold)} 金 / ${fmt(income.grain)} 粮 / ${fmt(income.manpower)} 预备兵</p></header>${domesticDirections(s,c,cityPersonnel(s,c.id),own&&isPlanning(s))}</section>`;
}
function cityPanel(s,c,ui){
  const own=c.owner===playerFaction(s),editable=isPlanning(s)&&own,income=cityIncome(s,c),officers=cityPersonnel(s,c.id);
  const military=cityMilitary(s,c),opening=siegeOpening(c,s.campaign.day);
  return `<div class="strategy-panel-body"><div class="panel-title"><span class="eyebrow">${FACTIONS[c.owner].name} · ${c.province}</span><h2>${c.name}</h2>${infoLink('city',c.id,'查看据点详情')}</div><div class="strategy-stats"><span>存粮<b>${fmt(c.grain)} / ${fmt(grainCapacity(c))}</b></span><span>预备兵<b>${fmt(c.manpower)}</b><small>已预留 ${fmt(c.domestic.reserved)}</small></span><span>城内士兵<b>${fmt(military.troops)}</b><small>${military.units}支部队</small></span><span>城内伤兵<b>${fmt(military.wounded)}</b></span><span>城门耐久<b>${fmt(c.gateHp)} / ${fmt(12000+c.walls*3000)}</b></span><span>守城首发<b>战意 +${Math.floor(opening.intent)} · 护盾 ${Math.round(opening.shield*100)}%</b></span></div><p class="strategy-muted">每旬预计：${fmt(income.gold)} 金 · ${fmt(income.grain)} 粮 · ${fmt(income.manpower)} 预备兵。</p>
  ${own?`<section class="city-command-hub"><span class="eyebrow">城中议事</span><h3>命令</h3><div class="command-choices">${button('campaign-pick','内政委任',!editable,`data-task="domestic" data-town="${c.id}"`)}${button('campaign-pick','调任武将',!editable,`data-task="transfer" data-town="${c.id}"`)}${button('campaign-pick','部队编制',!editable,`data-task="draft" data-town="${c.id}"`)}${button('campaign-pick','军团出征',!editable,`data-task="expedition" data-town="${c.id}"`)}</div></section><details class="city-affairs" data-city-disclosure="${c.id}:offices" ${ui.cityDisclosures?.[c.id+':offices']?'open':''}><summary>太守与军费</summary><div class="governor-slot"><div><small>太守</small><b>${esc(OFFICER_BY_ID[c.governor]?.name||'未任命')}</b></div>${button('campaign-pick','任命',!editable,`data-task="governor" data-town="${c.id}"`)}${c.governor?button('campaign-clear-governor','解除',!editable,`data-town="${c.id}"`):''}</div>
  ${domesticReference()}${governorSkillList(s,c).map(p=>abilityButton('trait',p.id,p.name)).join('')}
  <label class="strategy-field">全势力保留军费<input id="domestic-reserve" type="number" min="0" max="1000000" step="100" value="${s.campaign.domestic.reserveGold}" ${editable?'':'disabled'}></label>
  </details><details class="city-affairs" data-city-disclosure="${c.id}:affairs" ${ui.cityDisclosures?.[c.id+':affairs']?'open':''}><summary>内政</summary>${domesticDirections(s,c,officers,editable)}</details>
  <details class="city-affairs"><summary>驻城部队 · ${c.units.length} 队</summary><div class="strategy-officers">${c.units.map(u=>`<div><button class="personnel-name" data-action="campaign-person-detail" data-officer="${u.id}">${esc(u.name)} ↗</button><span>${TROOPS[u.type].name} · ${fmt(u.troops)} 人</span></div>`).join('')||'<p>尚未编制部队。</p>'}</div></details><section class="domestic-tech"><h3>兵种技术</h3><p>${c.domestic.techs.map(t=>detailLink('技术说明',[{name:TROOPS[t].name,rows:[[TROOPS[t].name,'','本城已掌握，可用于部队编制。']]}],TROOPS[t].name)).join('')}</p>${c.domestic.research?`${detailLink('技术说明',[{name:TECHS[c.domestic.research.type].name,rows:[['研究进度','',c.domestic.research.progress+'%'],['研究','', '技术负责人自动推进研究，完成后可编制对应兵种。']]}],TECHS[c.domestic.research.type].name)}<b>${c.domestic.research.progress}%</b><progress max="100" value="${c.domestic.research.progress}"></progress>`:'<small>技术负责人自主选择尚未掌握的兵种技术。</small>'}</section>
  <details class="domestic-facilities"><summary>设施</summary>
  ${c.project?`<div class="project-progress"><b>${PROJECTS[c.project.key].name}</b><span>还需 ${c.project.remaining} 旬 · 已开工</span></div>`:'<p class="strategy-muted">暂无在建工程</p>'}
  <div class="project-list">${Object.entries(PROJECTS).map(([key,p])=>`<article><div><b>${p.name} <small>Lv.${c[p.field]}</small></b>${buildingReference(c,key)}</div></article>`).join('')}</div>
  </details>${talentPanel(s)}`:'<p class="strategy-muted">占领后可安排内政、征募与补给。</p>'}</div>`;
}
function talentPanel(s){
 const info=talentSummary(s);
 return `<details class="talent-panel"><summary>人才接洽 · ${info.N}人</summary><p class="strategy-muted">意愿满 60 可接洽。</p>${info.people.map(p=>`<p><b>${esc(OFFICER_BY_ID[p.id].name)}</b> · ${p.locationConfirmed?esc(s.cities.find(c=>c.id===p.lastKnownCityId)?.name):'原位置线索已失效'}${p.locationConfirmed?` · ${p.phase==='SEEK'?'求仕中':'暂不求仕'} · 意愿${p.W}${p.H?' · 旧主顾虑-'+p.H:''}`:''}<br>接洽 ${p.progress}/${p.need} · ${esc(TALENT_REASONS[p.reason]||({signed:'已加入', 'other-faction':'已接受其他势力邀请'}[p.reason])||'等待接洽')}</p>`).join('')||'<p>暂无人才线索</p>'}<details><summary>人才重要报告</summary>${info.reports.map(r=>`<p>第${r.day}天 · ${esc(r.text)}</p>`).join('')||'<p>暂无变化。</p>'}</details></details>`;
}
function armyPanel(s,a){
  if(!a)return '<div class="strategy-panel-body">尚无出征军团。请在城市「城中议事」选择出征，先编组部队再下令。</div>';
  const own=a.faction===playerFaction(s),can=canEditArmy(s,a),r=armyBattle(s,a.id),need=dailyConsumption(s,a),connection=supplyConnection(s,a),byId=id=>mapNode(s,id),location=a.travel?`${byId(a.travel.from).name} → ${byId(a.travel.to).name}`:byId(a.location).name;
  return `<div class="strategy-panel-body"><label class="strategy-field">所选军团<select id="army-select">${s.armies.filter(x=>!x.defense).map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>${x.name} · ${FACTIONS[x.faction].name}</option>`).join('')}</select></label><h2>${esc(a.name)}</h2>${infoLink('army',a.id,'查看军团详情')}<p>${location} · ${armyWaitingOrder(s,a.id)?'等待内政完成后出发':r?'正在交战':a.task}</p><div class="strategy-stats"><span>编制<b>${a.units.filter(u=>u.troops>0).length} 队</b><small>待整编 ${a.units.filter(u=>u.troops===0).length} 人 · 出征最多10队</small></span><span>现役兵力<b>${fmt(liveSoldiers(s,a))}</b></span><span>每日行动力<b>${armyActionPoints(a).toFixed(1)} 点</b></span><span>每日耗粮<b>${need.toFixed(1)}</b></span><span>携粮<b>${fmt(a.supply)} / ${fmt(a.supplyCapacity)}</b></span><span>脱离补给可维持<b>${need?(a.supply/need).toFixed(1):'—'} 天</b></span></div>
  <div class="supply-status ${a.hunger?'danger':''}"><b>${connection?`粮道连接 · ${byId(connection.source).name}`:'粮道未连接'}</b><span>昨日运入 ${fmt(a.supplyIn)} · 缺粮程度 ${a.hunger.toFixed(1)} 天</span><small>${a.hunger?'缺粮削弱全军，累计五天部队自动解散。':'运输受据点库存、道路占领和通路容量限制。'}</small></div>
  ${a.route.length?`<p class="march-road-summary">${a.route.map((to,i)=>{const from=i?a.route[i-1]:a.location,road=i===0&&a.travel?(a.travel.road||'main'):a.roadPolicy;const cost=roadCost(s,from,to,road);return `${byId(from).name} → ${byId(to).name}：${campaignRoads(s,from,to).find(r=>r.cost===cost)?.name} ${cost} 点`;}).join('；')}</p>`:''}
  <p>行动力由最慢现役兵种、统帅、士气及缺粮决定；逐日消耗道路行动力，抵达据点后次日继续。</p>
  ${own?`<div class="strategy-actions">${button('campaign-order','调动军团',!isPlanning(s)||!!r)}${button('army','调整编制',!can)}${button('recruit','征募整补',!can)}</div>${r?button('campaign-focus','查看 / 接管战役',isPlanning(s),`data-battle="${r.id}"`):''}`:''}
  ${s.campaign.ai?.decisions.find(d=>d.armyId===a.id)?`<p class="strategy-muted"><b>军团方略</b> · ${esc(s.campaign.ai.decisions.find(d=>d.armyId===a.id).reason)}</p>`:''}
  <div class="strategy-officers">${a.units.map(u=>`<div><span>${u.name}<small>${u.troops>0?TROOPS[u.type].name:'随军待整编 · 暂不参战'} · 归属 ${byId(u.homeCity)?.name||'—'}</small></span><b>${fmt(u.troops)}<small>伤兵 ${fmt(u.wounded)}</small></b></div>`).join('')}</div></div>`;
}
function officerPanel(s,c){
 const all=campaignOfficers(s),local=all.filter(r=>r.location===c.id),own=c.owner===playerFaction(s),editable=isPlanning(s)&&own;
 return `<div class="strategy-panel-body"><div class="panel-title"><span class="eyebrow">麾下 ${all.length} 人 · 本据点 ${local.length} 人</span><h2>${esc(c.name)} · 人事</h2></div><div class="strategy-actions">${button('campaign-personnel','麾下武将一览')}${button('campaign-personnel','本据点武将',false,`data-town="${c.id}"`)}</div><div class="personnel-task-grid">${button('campaign-pick','预编守城部队',!editable,`data-task="draft" data-town="${c.id}"`)}${button('campaign-pick','调任武将',!editable,`data-task="transfer" data-town="${c.id}"`)}</div><div class="strategy-officers">${local.map(r=>`<div><button class="personnel-name" data-action="campaign-person-detail" data-officer="${r.unit.id}">${esc(r.unit.name)} ↗</button><span>${r.status}<small>${esc(r.duty)}</small></span></div>`).join('')||'<p>本据点暂无己方武将。</p>'}</div></div>`;
}
function cityDirectory(s,selected){
 const rows=campaignOfficers(s),towns=s.cities.filter(c=>c.owner===playerFaction(s));
 return `<section class="city-directory" aria-label="可操作城市列表"><header><h2>管辖据点 <small>${towns.length}</small></h2>${button('campaign-personnel','麾下武将 · '+rows.length+'人')}</header><div class="city-directory-list">${towns.map(c=>{const assigned=s.campaign.domestic.assignments.filter(a=>a.cityId===c.id);return `<button class="city-directory-item ${selected.id===c.id?'selected':''}" data-city="${c.id}" aria-pressed="${selected.id===c.id}"><span><b>${esc(c.name)}</b><small>${({city:'城市',gate:'关隘',port:'港口'})[c.kind]||'据点'} · ${rows.filter(r=>r.location===c.id).length}人</small></span><small>太守 ${esc(OFFICER_BY_ID[c.governor]?.name||'空缺')}</small><span class="city-duty-strip">${Object.entries(DIRECTIONS).map(([k,n])=>{const staff=assigned.filter(a=>a.direction===k);return `<i class="${staff.length?'staffed':'vacant'}" title="${n}：${staff.map(a=>OFFICER_BY_ID[a.officerId]?.name).join('、')||'未委任'}">${n.slice(0,1)} ${staff.length?'●':'○'}</i>`;}).join('')}</span></button>`;}).join('')||'<p>暂无管辖据点。</p>'}</div><small class="directory-key">● 已委任　○ 未委任 · 点击据点管理内政</small></section>`;
}
function battlesPanel(s,planning){return `<div class="strategy-panel-body"><h2>战役与每日快照</h2><p class="strategy-muted">接管当前状态；已经结算的日期不能重打。历史快照仅供查看。${s.campaign.scenarioId?'保留所有进行中战役和最近20场已结束战役的完整日快照；更早100场保留战报摘要。':''}</p>${[...s.campaign.battles].reverse().map(r=>`<article class="strategy-battle-card"><span class="eyebrow">第 ${r.startedDay} 天开战 · ${r.settled?'已结束':r.awaiting?'待决定':r.control==='manual'?'亲自指挥':'后台委托'}</span><h3>${esc(r.name)}</h3><p>${r.battle.sides.map(x=>FACTIONS[x.faction].name+' '+fmt(x.units.reduce((n,u)=>n+u.hp,0))+' 人').join(' / ')}</p><small>${r.snapshots.length} 份日快照${r.settled?' · '+r.report.reason:''}</small><div>${r.settled?'':button('campaign-focus',r.awaiting?'战前布阵':'接管当前战场',planning,`data-battle="${r.id}"`)}${button('campaign-history','查看每日快照',false,`data-battle="${r.id}"`)}</div></article>`).join('')||'<p>军团接触敌军后，战役将在这里显示。</p>'}${s.campaign.archive?.length?`<details><summary>较早战报 · ${s.campaign.archive.length} 场</summary>${s.campaign.archive.map(r=>`<p>第 ${r.startedDay}～${r.endedDay} 天 · ${esc(r.name)}<br>${r.winner?FACTIONS[r.winner].name+'获胜':'双方收兵'} · ${esc(r.reason)}</p>`).join('')}</details>`:''}</div>`;}
export function snapshotMarkup(s,r,requestedDay,sorting={}){
  const day=r.snapshots.some(x=>x.day===Number(requestedDay))?Number(requestedDay):r.snapshots.at(-1).day,b=readDailySnapshot(r,day);
  return `<p>每日快照只读。第 ${day} 天开始状态，已完成 ${b.tick} 日战斗。${r.settled?'本役已结束。':''}</p><label class="strategy-field">选择日期<select id="campaign-snapshot-day">${r.snapshots.map(x=>`<option value="${x.day}" ${x.day===day?'selected':''}>第 ${x.day} 天 · ${x.tick} 日</option>`).join('')}</select></label><div class="snapshot-board">${b.sides.flatMap(x=>x.units).filter(u=>u.status==='active').map(u=>`<span class="side-${u.side}" style="grid-column:${u.x+1};grid-row:${u.y+1}" title="${esc(u.name)}，${u.hp}人">${esc(u.name)}<small>${fmt(u.hp)}</small></span>`).join('')}</div><div class="snapshot-tables">${b.sides.map(side=>`<section><h3>${FACTIONS[side.faction].name}</h3><table><thead><tr>${[['name','部队'],['hp','余兵'],['intent','战意'],['status','状态']].map(([k,n])=>sortHeader('snapshot',k,n,sorting.sort,sorting.direction)).join('')}</tr></thead><tbody>${(sorting.sort?sortRows(side.units,sorting.sort,sorting.direction,(u,k)=>k==='status'?({active:'在场',reserve:'预备',defeated:'溃败',withdrawn:'撤离'})[u.status]:u[k]):side.units).map(u=>`<tr><td>${esc(u.name)}</td><td>${fmt(u.hp)}</td><td>${u.intent}</td><td>${({active:'在场',reserve:'预备',defeated:'溃败',withdrawn:'撤离'})[u.status]}</td></tr>`).join('')}</tbody></table></section>`).join('')}</div>${r.report?`<h3>最终战果 · ${r.report.reason}</h3>${(r.report.growth||[]).map(g=>`<p><b>${esc(g.name)}</b> · 功绩 +${g.gained} · ${g.after>g.before?`${g.before} → ${g.after}级`:`${g.after}级`}<br><small>${esc(contributionText(g.contribution))}${g.unlocked.length?` · 习得：${g.unlocked.map(esc).join("、")}`:""}</small></p>`).join('')}${r.report.stats.map(x=>`<p>${FACTIONS[x.faction].name}：余兵 ${fmt(x.remaining)}，伤兵 ${fmt(x.wounded)}，阵亡 ${fmt(x.killed)}，逃散 ${fmt(x.escaped)}</p>`).join('')}`:''}<div class="battle-logs">${b.logs.slice(0,8).map(x=>`<p>${x.tick} 日 · ${esc(x.text)}</p>`).join('')}</div>`;
}
