import {CAMPAIGN,PROJECTS,calendar,isPlanning,activeBattles,armyBattle,armyPosition,armySpeed,liveSoldiers,dailyConsumption,cityIncome,canEditArmy,readDailySnapshot,supplyConnection} from './strategic-campaign.mjs';
import {FACTIONS,TROOPS} from './engine.mjs';
import {BATTLE_TERRAINS} from './battlefield.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.round(n).toLocaleString('zh-CN');
const button=(action,label,disabled=false,extra='')=>`<button class="button secondary" data-action="${action}" ${disabled?'disabled':''} ${extra}>${label}</button>`;
export function campaignBattleBar(s){const d=calendar(s),r=s.campaign.battles.find(r=>r.id===s.campaign.focusId);return `<div id="campaign-battle-bar" class="campaign-battle-bar"><span><b>第 ${d.turn} 旬 · 第 ${d.dayInTurn} 天</b>　世界第 ${d.day} 天 · 交战第 ${d.day-(r?.startedDay||d.day)+1} 天 · 日内 ${s.campaign.stepInDay}/${CAMPAIGN.stepsPerDay}</span><div>${button('campaign-day','推进本日')}${button('campaign-map','交还委托 · 返回大地图')}</div></div>`;}
export function strategicView(s,ui){
  const d=calendar(s),planning=isPlanning(s),a=s.armies.find(a=>a.id===ui.army)||s.armies.find(a=>a.faction==='cao'),selected=s.cities.find(c=>c.id===ui.city)||s.cities.find(c=>c.owner==='cao')||s.cities[0];
  const live=activeBattles(s),pending=live.filter(r=>r.awaiting),tabs={city:'城池内政',army:'军团调度',officers:'在城武将',battles:'战役与快照'};
  const tab=ui.strategyTab||'city';
  return `<main class="campaign strategy-page"><header class="strategy-heading"><div><span class="eyebrow">军国大事 · 旬回合筹划 / 逐日执行</span><h1>天下大势</h1><p>一旬十天，战役一回合一天。所有战场共享同一日历。</p></div><div>${button('lobby','战役首页')}${button('settings','存档与设置')}${button('journal','天下纪事')}</div></header>
  <section class="strategy-clock"><div><strong>第 ${d.turn} 旬</strong><span>世界第 ${d.day} 天 · 本旬第 ${d.dayInTurn} 天</span></div><div class="day-track">${Array.from({length:10},(_,i)=>`<i class="${i+1<d.dayInTurn?'done':i+1===d.dayInTurn?'current':''}">${i+1}</i>`).join('')}</div><div><b>${planning?'战略筹划 · 全局暂停':ui.paused?'世界已暂停':'执行中'}</b><small>${live.length} 处交战 · 府库 ${fmt(s.gold)} 金 · 城内粮草 ${fmt(s.grain)}</small></div><div class="strategy-clock-actions">${planning?`<button class="button primary" data-action="campaign-begin" ${s.finished?'disabled':''}>进行 · 执行本旬</button>`:button('campaign-run',ui.paused?'继续进行':'暂停世界',pending.length>0||!!s.finished)}${button('campaign-day','推进一天',planning||pending.length>0||!!s.finished)}</div></section>
  <div class="strategy-notice" role="status">${esc(s.finished?(s.finished==='victory'?'中原已定，本局胜利。':'城池尽失，本局结束。'):s.campaign.lastNotice)}</div>
  ${pending.map(r=>`<section class="encounter-callout"><div><b>新遭遇 · ${esc(r.name)}</b><span>第 ${r.startedDay} 天 · ${BATTLE_TERRAINS[r.battle.terrain]} · ${r.battle.sides.map(x=>fmt(x.units.reduce((n,u)=>n+u.hp,0))+' 人').join(' 对 ')}</span></div><div>${button('campaign-manual','亲自指挥 · 战前布阵',false,`data-battle="${r.id}"`)}${button('campaign-auto','委托作战',false,`data-battle="${r.id}"`)}</div></section>`).join('')}
  <div class="strategy-layout"><section class="strategy-map-panel"><div class="strategy-map-caption"><b>中原战区</b><span><i class="legend-own"></i>曹军　<i class="legend-enemy"></i>敌军　<span class="supply-key">虚线：所选军团粮道</span></span></div>${map(s,ui,a)}<div class="strategy-map-caption"><span>点击城池查看内政，点击军团旗帜查看兵力与粮道。</span><b>${s.armies.filter(a=>a.route.length&&!armyBattle(s,a.id)).length} 支军团行军中</b></div></section>
  <aside class="strategy-panel"><nav class="strategy-tabs">${Object.entries(tabs).map(([key,label])=>`<button data-action="campaign-tab" data-tab="${key}" class="${tab===key?'active':''}">${label}</button>`).join('')}</nav>${tab==='city'?cityPanel(s,selected):tab==='army'?armyPanel(s,a):tab==='officers'?officerPanel(s,selected):battlesPanel(s,planning)}</aside></div>
  ${s.campaign.turnReports.length?`<details class="strategy-ledger"><summary>上旬收支与建设 · 第 ${s.campaign.turnReports[0].turn} 旬</summary>${s.campaign.turnReports[0].items.map(x=>`<p>${esc(x)}</p>`).join('')}</details>`:''}
  <footer class="strategy-footer">内政与军令在旬首安排。战役中可随时暂停下令，跨旬自动返回战略筹划。后台按日仿真，历史快照只读。</footer></main>`;
}
function map(s,ui,a){
  const byId=id=>s.cities.find(c=>c.id===id),selected=ui.city,line=a?supplyConnection(s,a):null;
  const legs=line?line.path.slice(1).map((id,i)=>[byId(line.path[i]),byId(id)]):[];
  if(line&&a.travel)legs.push([byId(a.location),armyPosition(s,a)]);
  const previous=ui.armyPositions||{};ui.armyPositions={};
  return `<svg class="strategy-world" viewBox="100 25 820 760" aria-label="中原军团与粮道地图"><defs><pattern id="strategy-grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="#899b85" stroke-opacity=".055"/></pattern></defs><rect x="100" y="25" width="820" height="760" fill="url(#strategy-grid)"/><path d="M150 175 Q280 130 400 220 T780 210 Q800 255 900 300" class="strategy-river"/><text x="610" y="208" class="river-label">黄 河</text><path d="M170 100l40-40 40 40m-30 0 45-60 45 60M150 410l35-50 35 50m-10 0 40-65 40 65" class="strategy-mountains"/>
  ${s.roads.map(([x,y])=>`<path d="M${byId(x).x} ${byId(x).y}L${byId(y).x} ${byId(y).y}" class="strategy-road"/>`).join('')}
  ${a?.route.length?`<polyline points="${[armyPosition(s,a),...a.route.map(byId)].map(p=>`${p.x},${p.y}`).join(' ')}" class="strategy-order-path"/>`:''}
  ${legs.map(([x,y])=>`<path d="M${x.x} ${x.y}L${y.x} ${y.y}" class="strategy-supply-path"/>`).join('')}
  ${s.cities.map(c=>`<g data-city="${c.id}" tabindex="0" role="button" aria-label="${c.name}，${FACTIONS[c.owner].name}" class="strategy-city ${c.owner} ${selected===c.id?'selected':''}" transform="translate(${c.x} ${c.y})"><circle r="27"/><path d="M-14 11V-5h5v-9h5v7h8v-7h5v9h5v16Z"/><text y="48">${c.name}</text><text class="city-stock" y="64">粮 ${fmt(c.grain)}</text></g>`).join('')}
  ${s.armies.filter(a=>!a.disbanded).map((a,index)=>{const p=armyPosition(s,a),offset=a.travel?0:(index%3-1)*23,present={x:p.x+offset,y:p.y-42};ui.armyPositions[a.id]=present;const old=previous[a.id]||present;
    return `<g role="button" tabindex="0" data-campaign-army="${a.id}" aria-label="${esc(a.name)}，${fmt(liveSoldiers(s,a))}人" class="strategy-army ${a.faction} ${ui.army===a.id?'selected':''}" transform="translate(${present.x} ${present.y})"><animateTransform attributeName="transform" type="translate" from="${old.x} ${old.y}" to="${present.x} ${present.y}" dur=".65s" fill="freeze"/><path d="M0 0V-30H51L43-18l8 12H0"/><text x="24" y="-14">${FACTIONS[a.faction].short} ${Math.round(liveSoldiers(s,a)/100)/10}千</text><title>${esc(a.name)} · ${armyBattle(s,a.id)?'交战':a.task} · 日速 ${armySpeed(a)} 公里</title></g>`;}).join('')}
  ${activeBattles(s).map(r=>`<g class="strategy-battle-marker" data-action="campaign-focus" data-battle="${r.id}" tabindex="0" role="button" aria-label="${esc(r.name)}" transform="translate(${r.point.x} ${r.point.y+22})"><circle r="15"/><text y="5">战</text></g>`).join('')}</svg>`;
}
function cityPanel(s,c){
  const own=c.owner==='cao',editable=isPlanning(s)&&own,income=cityIncome(s,c),officers=s.campaign.idle.filter(o=>o.location===c.id&&!o.destination&&o.faction===c.owner);
  return `<div class="strategy-panel-body"><div class="panel-title"><span class="eyebrow">${FACTIONS[c.owner].name} · ${c.province}</span><h2>${c.name}</h2></div><div class="strategy-stats"><span>存粮<b>${fmt(c.grain)} / ${fmt(10000+c.granary*10000)}</b></span><span>兵源<b>${fmt(c.manpower)}</b></span><span>民心<b>${c.order} / 100</b></span><span>城门耐久<b>${fmt(c.gateHp)}</b></span></div><p class="strategy-muted">每旬预计：${fmt(income.gold)} 金 · ${fmt(income.grain)} 粮 · ${fmt(income.manpower)} 兵源。被围城时停产。</p>
  ${own?`<label class="strategy-field">太守<select id="campaign-governor" data-town="${c.id}" ${editable?'':'disabled'}><option value="">暂不任命</option>${officers.map(o=>`<option value="${o.unit.id}" ${c.governor===o.unit.id?'selected':''}>${o.unit.name} · 政治 ${o.unit.politics}</option>`).join('')}</select></label><p class="strategy-muted">太守留驻本城，政治提升产出。任职期间不能编军出征。</p>
  ${c.project?`<div class="project-progress"><b>${PROJECTS[c.project.key].name}</b><span>还需 ${c.project.remaining} 旬 · 已开工</span></div>`:'<p class="strategy-muted">每城一个建设队列，最高五级。</p>'}
  <div class="project-list">${Object.entries(PROJECTS).map(([key,p])=>`<article><div><b>${p.name} <small>Lv.${c[p.field]}</small></b><small>${p.description}</small></div>${button('campaign-project',`${p.cost} 金 · ${p.turns} 旬`,!editable||!!c.project||c[p.field]>=5||s.gold<p.cost,`data-town="${c.id}" data-project="${key}"`)}</article>`).join('')}</div>
  ${button('campaign-relief','赈济安民 · 150 金 / 300 粮',!editable||c.reliefTurn===s.turn||c.order>=100,`data-town="${c.id}"`)}<p class="strategy-muted">民心 +15，每旬一次。民心影响生产与兵源恢复。</p>`:'<p class="strategy-muted">占领后可安排内政、征募与补给。</p>'}</div>`;
}
function armyPanel(s,a){
  if(!a)return '<div class="strategy-panel-body">尚无军团，可在「在城武将」中组建。</div>';
  const own=a.faction==='cao',can=canEditArmy(s,a),r=armyBattle(s,a.id),need=dailyConsumption(s,a),connection=supplyConnection(s,a),byId=id=>s.cities.find(c=>c.id===id),location=a.travel?`${byId(a.travel.from).name} → ${byId(a.travel.to).name}`:byId(a.location).name;
  return `<div class="strategy-panel-body"><label class="strategy-field">所选军团<select id="army-select">${s.armies.map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>${x.name} · ${FACTIONS[x.faction].name}</option>`).join('')}</select></label><h2>${esc(a.name)}</h2><p>${location} · ${r?'正在交战':a.task}</p><div class="strategy-stats"><span>编制<b>${a.units.length} / 10 队</b></span><span>现役兵力<b>${fmt(liveSoldiers(s,a))}</b></span><span>每日行军<b>${armySpeed(a)} 公里</b></span><span>每日耗粮<b>${need.toFixed(1)}</b></span><span>携粮<b>${fmt(a.supply)} / ${fmt(a.supplyCapacity)}</b></span><span>脱离补给可维持<b>${need?(a.supply/need).toFixed(1):'—'} 天</b></span></div>
  <div class="supply-status ${a.hunger?'danger':''}"><b>${connection?`粮道连接 · ${byId(connection.source).name}`:'粮道未连接'}</b><span>昨日运入 ${fmt(a.supplyIn)} · 缺粮程度 ${a.hunger.toFixed(1)} 天</span><small>${a.hunger?'缺粮削弱全军，累计五天部队自动解散。':'运输受据点库存、道路占领和通路容量限制。'}</small></div>
  ${own?`<label class="strategy-field">目的地<select id="campaign-target" ${isPlanning(s)&&!r?'':'disabled'}>${s.cities.map(c=>`<option value="${c.id}" ${c.id===(a.target||'guandu')?'selected':''}>${c.name} · ${FACTIONS[c.owner].name}</option>`).join('')}</select></label><div class="strategy-actions">${button('campaign-order','下达行军令',!isPlanning(s)||!!r)}${button('army','调整编制',!can)}${button('recruit','征募整补',!can)}</div>${r?button('campaign-focus','查看 / 接管战役',isPlanning(s),`data-battle="${r.id}"`):''}`:''}
  <div class="strategy-officers">${a.units.map(u=>`<div><span>${u.name}<small>${TROOPS[u.type].name} · 归属 ${byId(u.homeCity)?.name||'—'}</small></span><b>${fmt(u.troops)}<small>伤兵 ${fmt(u.wounded)}</small></b></div>`).join('')}</div></div>`;
}
function officerPanel(s,c){
  const idle=s.campaign.idle.filter(o=>o.faction==='cao'),towns=s.cities.filter(x=>x.owner==='cao'),editing=isPlanning(s),inCity=idle.filter(o=>o.location===c.id&&!o.destination);
  return `<div class="strategy-panel-body"><h2>${c.name} · 在城武将</h2><p class="strategy-muted">选择本城待命武将组建军团，最多十队；随后在军团调度中征募整补。</p><div class="strategy-officers">${inCity.map(o=>{const governor=s.cities.some(x=>x.governor===o.unit.id);return `<div><label><input type="checkbox" data-draft-officer="${o.unit.id}" ${!editing||governor?'disabled':''}> ${o.unit.name}<small>统 ${o.unit.leadership} · 武 ${o.unit.force} · 智 ${o.unit.intellect} · 政 ${o.unit.politics}${governor?' · 太守':''}</small></label></div>`;}).join('')||'<p>暂无待命武将。</p>'}</div>${button('campaign-create-army','编制新军团',!editing||c.owner!=='cao',`data-town="${c.id}"`)}
  <h3>调任与返城</h3>${idle.map(o=>`<div class="officer-transfer"><b>${o.unit.name}</b><span>${o.destination?`前往 ${s.cities.find(c=>c.id===o.destination).name} · 还需 ${o.remainingDays} 天`:s.cities.find(c=>c.id===o.location).name+'待命'}</span>${!o.destination?`<select data-transfer-target="${o.unit.id}" ${editing?'':'disabled'}>${towns.map(c=>`<option value="${c.id}" ${c.id===o.location?'selected':''}>${c.name}</option>`).join('')}</select>${button('campaign-transfer','调任',!editing,`data-officer="${o.unit.id}"`)}`:''}</div>`).join('')}<p class="strategy-muted">调任需要真实行程。出征武将保留归属城池，可在军团调度中查看。</p></div>`;
}
function battlesPanel(s,planning){return `<div class="strategy-panel-body"><h2>战役与每日快照</h2><p class="strategy-muted">接管当前状态；已经结算的日期不能重打。历史快照仅供查看。</p>${[...s.campaign.battles].reverse().map(r=>`<article class="strategy-battle-card"><span class="eyebrow">第 ${r.startedDay} 天开战 · ${r.settled?'已结束':r.awaiting?'待决定':r.control==='manual'?'亲自指挥':'后台委托'}</span><h3>${esc(r.name)}</h3><p>${r.battle.sides.map(x=>FACTIONS[x.faction].name+' '+fmt(x.units.reduce((n,u)=>n+u.hp,0))+' 人').join(' / ')}</p><small>${r.snapshots.length} 份日快照${r.settled?' · '+r.report.reason:''}</small><div>${r.settled?'':button('campaign-focus',r.awaiting?'战前布阵':'接管当前战场',planning,`data-battle="${r.id}"`)}${button('campaign-history','查看每日快照',false,`data-battle="${r.id}"`)}</div></article>`).join('')||'<p>军团接触敌军后，战役将在这里显示。</p>'}</div>`;}
export function snapshotMarkup(s,r,requestedDay){
  const day=r.snapshots.some(x=>x.day===Number(requestedDay))?Number(requestedDay):r.snapshots.at(-1).day,b=readDailySnapshot(r,day);
  return `<p>每日快照只读。第 ${day} 天开始状态，已完成 ${b.tick} 个战斗结算步。${r.settled?'本役已结束。':''}</p><label class="strategy-field">选择日期<select id="campaign-snapshot-day">${r.snapshots.map(x=>`<option value="${x.day}" ${x.day===day?'selected':''}>第 ${x.day} 天 · ${x.tick} 步</option>`).join('')}</select></label><div class="snapshot-board">${b.sides.flatMap(x=>x.units).filter(u=>u.status==='active').map(u=>`<span class="side-${u.side}" style="grid-column:${u.x+1};grid-row:${u.y+1}" title="${esc(u.name)}，${u.hp}人">${esc(u.name)}<small>${fmt(u.hp)}</small></span>`).join('')}</div><div class="snapshot-tables">${b.sides.map(side=>`<section><h3>${FACTIONS[side.faction].name}</h3><table><thead><tr><th>部队</th><th>余兵</th><th>战意</th><th>状态</th></tr></thead><tbody>${side.units.map(u=>`<tr><td>${esc(u.name)}</td><td>${fmt(u.hp)}</td><td>${u.intent}</td><td>${({active:'在场',reserve:'预备',defeated:'溃败',withdrawn:'撤离'})[u.status]}</td></tr>`).join('')}</tbody></table></section>`).join('')}</div>${r.report?`<h3>最终战果 · ${r.report.reason}</h3>${r.report.stats.map(x=>`<p>${FACTIONS[x.faction].name}：余兵 ${fmt(x.remaining)}，伤兵 ${fmt(x.wounded)}，阵亡 ${fmt(x.killed)}，逃散 ${fmt(x.escaped)}</p>`).join('')}`:''}<div class="battle-logs">${b.logs.slice(0,8).map(x=>`<p>${x.tick} 步 · ${esc(x.text)}</p>`).join('')}</div>`;
}
