import {TECHS,TECHNOLOGY_BRANCHES,TECHNOLOGY_AFFINITIES,cityTechnologyProfile,technologyAllowed,technologyRequirements,technologyConditionText,knowsTechnology,localTechnologies,cityVisionRadius} from './city-technology.mjs';
import {researchDailyRate,besieged} from './domestic.mjs';
import {TROOP_DESIGNS} from './data/design/troops.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>Number(n.toFixed(1));
export function technologyMarkup(s,c){
 const profile=cityTechnologyProfile(c);if(!c?.domestic||!profile)return '';
 const active=c.domestic.research,assignment=s.campaign.domestic.assignments.find(a=>a.cityId===c.id&&a.action?.targetId===active?.type&&a.direction==='technology'),rate=assignment?researchDailyRate(s,c,assignment):0;
 const halted=active&&(besieged(s,c.id)||assignment?.action.paused),days=active&&rate>0?Math.ceil((100-active.progress)/rate):null;
 const card=id=>{
  const t=TECHS[id],known=knowsTechnology(c,id),allowed=technologyAllowed(c,id),researching=active?.type===id,reasons=known||researching?[]:technologyRequirements(c,id),state=known?'complete':researching?'researching':!allowed?'foreign':reasons.length?'locked':'ready';
  return `<article class="technology-node is-${state}" data-technology="${id}" data-technology-state="${state}"><div class="technology-node-title"><b>${esc(t.name)}</b><span>${known?'已掌握':researching?'研究中':!allowed?'本城无资质':reasons.length?'条件未满足':'可研究'}</span></div><p>${esc(t.description)}</p>${t.prerequisites.length?`<small class="technology-parent">↳ ${t.prerequisites.map(p=>esc(TECHS[p].name)).join('、')}</small>`:''}<small>${t.cost}金 · 基准${t.days}天</small><details><summary>研究条件</summary><p>${esc(technologyConditionText(id,c))}</p>${reasons.length?`<p class="technology-missing">当前缺少：${esc(reasons.join('、'))}</p>`:''}</details></article>`;
 };
 const local=localTechnologies(c),others=Object.keys(TECHS).filter(id=>!technologyAllowed(c,id));
 return `<section class="domestic-tech technology-tree" data-city-technology="${esc(c.id)}"><h3>城市科技树</h3><p class="technology-profile">${profile.affinities.map(a=>esc(TECHNOLOGY_AFFINITIES[a])).join(' · ')} · 特色兵种：${profile.troops.map(id=>esc(TROOP_DESIGNS[id].name)).join('、')} · 本城开放${local.length}项</p>${active?`<div class="technology-progress" role="status"><b>${esc(TECHS[active.type].name)} · ${pct(active.progress)}%</b><progress max="100" value="${active.progress}" aria-label="${esc(TECHS[active.type].name)}研究进度"></progress><small>已研究${active.workedDays}个工作日 · 已付${active.spent}金 · ${halted?'围城暂停':!assignment?'等待技术负责人接续':days===null?'本轮研制受阻，结束后继续评估':`预计还需${days}个工作日`}</small></div>`:'<p class="technology-help">委任技术负责人后自动选择符合条件的科技；每城同时研究一项，多人可协作。智力和工坊影响进度。</p>'}${cityVisionRadius(c,0)>0?`<p class="technology-tower">瞭望塔持续警戒 · 视野半径${cityVisionRadius(c,0)}</p>`:''}<div class="technology-branches">${Object.entries(TECHNOLOGY_BRANCHES).map(([branch,name])=>`<section class="technology-branch"><h4>${name}</h4><div class="technology-levels">${[1,2].map(tier=>`<div class="technology-level" data-technology-tier="${tier}"><small>${tier===1?'基础':'进阶'}</small>${local.filter(id=>TECHS[id].branch===branch&&TECHS[id].tier===tier).map(card).join('')||'<p class="technology-empty">本城无此方向的进阶科技</p>'}</div>`).join('')}</div></section>`).join('')}</div><details class="technology-other"><summary>其它城市科技（${others.length}项）</summary><div class="technology-other-nodes">${others.map(card).join('')}</div></details></section>`;
}
