import test from 'node:test';import assert from 'node:assert/strict';import{createScenario}from'../scenarios.mjs';import{lockDeployment,stepBattle,validateSave,reserveDeploymentUnit}from'../engine.mjs';import{setStatus,hasStatus,unitTactics}from'../tactics.mjs';import{OFFICER_DESIGNS as O}from'../data/design/officers.mjs';import{splitPeachDamage,peachInvincible}from'../bond-reserves-peach.mjs';import{grantBondEntries,bondAttributes}from'../bonds.mjs';import{bondSummary}from'../bond-display.mjs';
const id=n=>Object.values(O).find(o=>o.name===n).id,team=names=>names.map(name=>({id:id(name),type:'spear',troops:4000,level:10}));
function scene(own=['刘备','关羽','张飞'],enemy=['吕布','典韦','许褚'],side=0){return createScenario('custom-battle',8585,20,null,{seed:8585,terrain:'land',ownTeam:team(side?enemy:own),enemyTeam:team(side?own:enemy)});}
function quiet(b){for(const u of b.sides.flatMap(s=>s.units)){u.cooldown=999;u.skillReady=Object.fromEntries(u.tactics.map(id=>[id,999]));u.retreatAt=null;}}
function burn(b,u,amount){const source=b.sides[1-u.side].units[0];setStatus(b,u,'burn',2,{amount,sourceId:source.id,sourceName:source.name,sourceSkillName:'火矢'});}
function hp(u,n){u.hp=n;u.battleDamage=u.initial-n;u.healed=0;}
test('finite-capacity equal sharing redistributes overkill without creating damage or losing it to a tiny unit',()=>{const us=[{hp:10},{hp:20},{hp:1000}];assert.deepEqual([...splitPeachDamage(300,us,u=>u.hp).values()],[10,20,270]);assert.deepEqual([...splitPeachDamage(9,us,u=>u.hp).values()],[3,3,3]);assert.equal([...splitPeachDamage(2000,us,u=>u.hp).values()].reduce((a,b)=>a+b,0),1030);});
test('real enemy damage shares equally on either side; recipient shields absorb their own shares and saves resume',()=>{for(const side of [0,1]){const s=scene(undefined,undefined,side),b=s.battle;lockDeployment(b);quiet(b);const us=b.sides[side].units;setStatus(b,us[1],'shield',5,{amount:500,source:'test',label:'测试护盾'});burn(b,us[0],900);const copy=validateSave(structuredClone(s));stepBattle(b);stepBattle(copy.battle);assert.deepEqual(s,copy);assert.equal(us[0].initial-us[0].hp,300);assert.equal(us[1].initial-us[1].hp,0);assert.equal(us[2].initial-us[2].hp,300);assert.equal(us[1].statuses.shield.amount,200);assert.equal(b.effects.filter(e=>e.text==='桃园分担').length,2);validateSave(structuredClone(s));}});
test('two actual defeats in one damage packet grant the triple survivor fury and actionable invulnerability exactly once',()=>{const s=scene(),b=s.battle;lockDeployment(b);quiet(b);const [a,c,last]=b.sides[0].units;hp(a,10);hp(c,20);burn(b,a,300);stepBattle(b);assert.equal(a.status,'defeated');assert.equal(c.status,'defeated');assert.equal(last.hp,3730);assert.ok(last.statuses.peachFury);assert.ok(peachInvincible(b,last));assert.equal(b.sides[0].bondPeach.defeated.length,2);assert.equal(bondAttributes(b,last).attack.find(x=>x.label==='桃园奋战').factor,1.4);const until=last.statuses.peachInvincible.until;
 burn(b,last,900);last.cooldown=0;Object.assign(last,{x:4,y:3});Object.assign(b.sides[1].units[0],{x:5,y:3});const before=last.hp;stepBattle(b);assert.equal(last.hp,before);assert.ok(b.effects.some(e=>e.from===last.id&&!e.skill&&e.damage>0),'invulnerability must allow normal attacks');assert.equal(last.statuses.peachInvincible.until,until);const copy=validateSave(structuredClone(s));for(let i=0;i<5&&!b.result;i++){stepBattle(b);stepBattle(copy.battle);}assert.deepEqual(s,copy);assert.equal(peachInvincible(b,last),false);});
test('one casualty grants two-member fury but never triple invulnerability; full simultaneous wipe cannot be rescued',()=>{const s=scene(['刘备','关羽']),b=s.battle;lockDeployment(b);quiet(b);hp(b.sides[0].units[0],10);burn(b,b.sides[0].units[0],100);stepBattle(b);assert.ok(b.sides[0].units[1].statuses.peachFury);assert.equal(b.sides[0].units[1].statuses.peachInvincible,undefined);const wipe=scene(),w=wipe.battle;lockDeployment(w);quiet(w);for(const u of w.sides[0].units)hp(u,10);burn(w,w.sides[0].units[0],900);stepBattle(w);assert.ok(w.sides[0].units.every(u=>u.status==='defeated'&&!u.statuses.peachInvincible));});
test('reserve members do not link before arrival; lawful withdrawal does not trigger a death reward',()=>{const s=scene(),b=s.battle;reserveDeploymentUnit(b,id('张飞'));lockDeployment(b);assert.equal(b.sides[0].bondPeach.triple,false);assert.equal(b.sides[0].bondPeach.members.length,2);quiet(b);const a=b.sides[0].units.find(u=>u.id===id('刘备'));a.retreatAt=a.hp;for(let i=0;i<50&&a.status!=='withdrawn';i++)stepBattle(b);assert.equal(a.status,'withdrawn');assert.equal(b.sides[0].bondPeach.defeated.length,0);assert.ok(b.sides[0].units.every(u=>!u.statuses.peachFury));});
test('reserve quota is fixed at lock and the next three real entrants receive one ordinary small use even after providers withdraw',()=>{const own=['黄忠','徐晃','吕蒙','邓艾','关羽','张飞','刘备','赵云','马超'],s=scene(own),b=s.battle;lockDeployment(b);const opening=b.sides[0].units.filter(u=>u.status==='active');assert.equal(b.sides[0].bondReserve.tier,3);assert.deepEqual(b.sides[0].bondReserve.awarded,[]);quiet(b);for(const u of opening.slice(0,4))u.retreatAt=u.hp;
 for(let i=0;i<90&&b.sides[0].bondReserve.awarded.length<3&&!b.result;i++)stepBattle(b);const r=b.sides[0].bondReserve;assert.equal(r.awarded.length,3);assert.ok(opening.slice(0,4).every(u=>u.status==='withdrawn'));for(const a of r.awarded){const u=b.sides[0].units.find(u=>u.id===a.id);assert.ok(u.intent>=20);assert.equal(u.tacticUseBonus[a.skill],1);assert.equal(unitTactics(u).find(t=>t.id===a.skill).learningTier,'low');assert.equal(u.skillReady[a.skill],999);}
 const snapshot=structuredClone(r);grantBondEntries(b);assert.deepEqual(r,snapshot);assert.equal(bondSummary([],b,0).find(d=>d.id==='bondReserve').remaining,0);const copy=validateSave(structuredClone(s));for(let i=0;i<8&&!b.result;i++){stepBattle(b);stepBattle(copy.battle);}assert.deepEqual(s,copy);const bad=structuredClone(s);bad.battle.sides[0].bondReserve.awarded.push({...r.awarded[0]});assert.throws(()=>validateSave(bad));});
