import test from 'node:test';import assert from 'node:assert/strict';
import {makeOfficer,TROOPS} from '../engine.mjs';import {TECHS,canTrain} from '../domestic.mjs';import {TRAIT_DESIGNS} from '../data/design/traits.mjs';import {officerTraits} from '../officer-traits.mjs';import {formationAura} from '../support-rules.mjs';import {BOND_ASSIGNMENTS} from '../data/design/bond-assignments.mjs';import {sideBonds,bondProtection} from '../bonds.mjs';import {pulseBondCombos} from '../bond-combos.mjs';import {shieldAmount} from '../tactics.mjs';
test('removed auxiliary troop and old aura cannot be acquired through traits or technology',()=>{assert.equal(TROOPS.logistics,undefined);assert.equal(TECHS.logistics,undefined);assert.equal(canTrain({domestic:{techs:['logistics']}},'logistics'),false);assert.equal(TRAIT_DESIGNS.formationSupport,undefined);for(const id of ['yu','ju','person-255']){const u=makeOfficer(id,3000);assert.ok(!officerTraits(u).includes('formationSupport'));assert.equal(u.tacticLearning.byTroop.logistics,undefined);assert.equal(formationAura({tick:0,sides:[{units:[u]},{units:[]}]},u),null);}});
test('current escort support uses low-strength shields rather than a standing aura and stops outside its radius',()=>{
 const ids=Object.entries(BOND_ASSIGNMENTS).filter(([,a])=>a.bondEscort).slice(0,3).map(([id])=>id),units=ids.map((id,i)=>({...makeOfficer(id,3000,0,10),side:0,hp:3000,maxHp:3000,status:'active',x:i+2,y:3,statuses:{},bondState:{}}));
 const b={tick:0,sides:[{units},{units:[]}]},target={...makeOfficer('person-1',3000,0,1),side:0,hp:1200,maxHp:3000,status:'active',x:3,y:4,statuses:{},bondState:{}};b.sides[0].units.push(target);assert.ok(sideBonds(b,0).bondEscort?.tier);assert.equal(bondProtection(b,target,'basic'),1);
 const api={signal:()=>{}};for(const u of units.filter(u=>u!==target))pulseBondCombos(b,u,null,api);assert.ok(shieldAmount(b,target)>0);assert.equal(target.hp,1200);
 target.statuses={};target.x=13;b.tick=6;for(const u of units.filter(u=>u!==target))pulseBondCombos(b,u,null,api);assert.equal(shieldAmount(b,target),0);
 target.x=3;for(const u of units.filter(u=>u!==target)){u.withdrawing=true;pulseBondCombos(b,u,null,api);}assert.equal(shieldAmount(b,target),0);
});
