import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm,readdir} from 'node:fs/promises';
import {join,resolve,dirname,basename} from 'node:path';
import {tmpdir} from 'node:os';
import {zipSync,unzipSync} from 'fflate';
import {createGameData,buildCodeRelease,sha256} from '../scripts/release-lib.mjs';
import {decodeDataPack,loadDataPack} from '../packaging/data-pack.mjs';
import {buildArtArchive} from '../scripts/build-art-pack.mjs';
import {readAssetArchive,validateArchiveEntries} from '../asset-archive.mjs';
import {serveAssets} from '../asset-server.mjs';

async function directory(t){const base=resolve(tmpdir()),dir=await mkdtemp(join(base,'sango-release-'));t.after(()=>{assert.equal(dirname(resolve(dir)),base);assert.ok(basename(dir).startsWith('sango-release-'));return rm(dir,{recursive:true,force:true});});return dir;}
test('all compiled tables retain their exact current values and a reproducible data revision',async()=>{
 const first=await createGameData(),second=await createGameData();
 assert.deepEqual(decodeDataPack(first.bytes,first.metadata).tables,first.tables);
 assert.deepEqual(first.bytes,second.bytes);assert.equal(first.metadata.sha256,sha256(first.bytes));
 assert.ok(first.bytes.length<first.metadata.decodedBytes);
 assert.throws(()=>JSON.parse(first.bytes.toString()),SyntaxError);
});
test('binary header, length, version and actual content checksum reject stale or corrupt data',async()=>{
 const pack=await createGameData();
 for(const offset of [0,8,12,16]){const bytes=Buffer.from(pack.bytes);bytes[offset]^=255;assert.throws(()=>decodeDataPack(bytes,pack.metadata));}
 assert.throws(()=>decodeDataPack(pack.bytes.subarray(0,15)));
 assert.throws(()=>decodeDataPack(pack.bytes,{...pack.metadata,rulesVersion:-1}),/版本/);
 const saved=globalThis.fetch;
 try{
  globalThis.fetch=async()=>new Response(pack.bytes);
  assert.deepEqual(await loadDataPack('http://test/data',pack.metadata),pack.tables);
  const corrupt=Buffer.from(pack.bytes);corrupt[corrupt.length-1]^=1;globalThis.fetch=async()=>new Response(corrupt);
  await assert.rejects(loadDataPack('http://test/data',pack.metadata),/校验/);
 }finally{globalThis.fetch=saved;}
});
test('a code-only release contains runtime bundles and binary tables without source tables or local artwork',async t=>{
 const dir=await directory(t),{manifest}=await buildCodeRelease(dir),files=await readdir(dir);
 for(const unwanted of ['data','vendor','assets','art','.local','packaging','tests','scripts','officers-source.json'])assert.ok(!files.includes(unwanted),unwanted);
 for(const file of ['app.js','app.css','game-data.bin','server.mjs','start-game.cmd','release.json','sw.js','index.html'])assert.ok(files.includes(file),file);
 assert.ok(!files.some(file=>file.endsWith('.map')));
 for(const [path,entry] of Object.entries(manifest.files))assert.equal(sha256(await readFile(join(dir,path))),entry.sha256);
 const code=await readFile(join(dir,'app.js'),'utf8');assert.doesNotMatch(code,/Generated by scripts\/import-officers|Source labels only|export const OFFICER_SOURCE/);
 assert.equal(manifest.codeOnly,true);assert.match(await readFile(join(dir,'sw.js'),'utf8'),/game-data\.bin/);
});
test('art archive preserves the public URL contract and excludes undeclared production records',async t=>{
 const dir=await directory(t),source=join(dir,'source'),target=join(dir,'packed');
 await mkdir(join(source,'town'),{recursive:true});
 await writeFile(join(source,'manifest.json'),JSON.stringify({version:1,id:'test',revision:'1',town:{art:{buildings:'./assets/town/approved.webp'}}}));
 await writeFile(join(source,'town/approved.webp'),'approved bytes');await writeFile(join(source,'candidate.png'),'candidate');await writeFile(join(source,'receipts.json'),'private');
 const built=await buildArtArchive(join(target,'art.pack'),source),pack=await readAssetArchive(target);
 assert.equal(built.files.length,2);assert.deepEqual([...pack.files.keys()],['manifest.json','town/approved.webp']);
 let status,body;const response={writeHead(value){status=value;},end(value){body=value;}};
 await serveAssets('/assets/town/approved.webp',response,target);assert.equal(status,200);assert.equal(Buffer.from(body).toString(),'approved bytes');
 await serveAssets('/assets/candidate.png',response,target);assert.equal(status,404);
 const entries=unzipSync(await readFile(join(target,'art.pack')));entries['private.json']=Buffer.from('private');assert.throws(()=>validateArchiveEntries(entries),/Undeclared/);
 delete entries['private.json'];entries['town/approved.webp'][0]^=1;assert.throws(()=>validateArchiveEntries(entries),/checksum/);
 await writeFile(join(target,'art.pack'),zipSync(entries));await assert.rejects(readAssetArchive(target),/checksum/);
});
test('published officer manifests keep presentation fields and omit embedded production metadata',async t=>{
 const dir=await directory(t),source=join(dir,'source'),url='./assets/officers/generated/v8/cao/portrait.png',image=Buffer.from('approved portrait');
 await mkdir(join(source,'officers/generated/v8/cao'),{recursive:true});await writeFile(join(source,'officers/generated/v8/cao/portrait.png'),image);
 await writeFile(join(source,'manifest.json'),JSON.stringify({version:1,id:'test',revision:'1',officers:'./assets/officers/manifest.json',town:{}}));
 await writeFile(join(source,'officers/manifest.json'),JSON.stringify({version:1,id:'original-officers',productionQueue:['private'],officers:{cao:{portrait:{url,width:1024,height:1024,sha256:sha256(image),fit:'contain',transparent:true,prompt:'private prompt',identityReference:'private identity'}}}}));
 const target=join(dir,'pack');await buildArtArchive(join(target,'art.pack'),source);const pack=await readAssetArchive(target);
 const text=Buffer.from(pack.files.get('officers/manifest.json')).toString(),manifest=JSON.parse(text);
 assert.doesNotMatch(text,/private|productionQueue|identityReference|prompt/);
 assert.equal(manifest.officers.cao.portrait.fit,'contain');assert.equal(manifest.officers.cao.portrait.transparent,true);assert.equal(manifest.officers.cao.portrait.sha256,sha256(image));
});
